import type { SpotProfile } from "./types";
import { getSpotSpec } from "@/lib/spot-specs";

/** Maps knowledge-base ids or aliases to catalog spot ids. */
export const SPOT_PROFILE_ALIASES: Record<string, string> = {
  "oceanside-pier": "oceanside",
  "cardiff-reef": "cardiff",
};

const DEFAULT_PROFILE: SpotProfile = {
  id: "default",
  breakType: "beach",
  idealSwellDegMin: 260,
  idealSwellDegMax: 310,
  amplificationFactor: 1.0,
  minPeriodSec: 8,
  tidePreference: "any",
  shadowSensitivity: 0.75,
};

function profileFromSpec(catalogId: string): SpotProfile | null {
  const spec = getSpotSpec(catalogId);
  if (!spec) return null;
  return {
    id: catalogId,
    breakType: spec.breakType,
    idealSwellDegMin: spec.swellDegMin,
    idealSwellDegMax: spec.swellDegMax,
    amplificationFactor: spec.amplificationFactor,
    minPeriodSec: spec.minPeriodSec,
    tidePreference: spec.tidePreference,
    shadowSensitivity: spec.shadowSensitivity,
  };
}

export const SPOT_PROFILES: Record<string, SpotProfile> = {
  malibu: {
    id: "malibu",
    breakType: "point",
    idealSwellDegMin: 250,
    idealSwellDegMax: 310,
    amplificationFactor: 1.12,
    minPeriodSec: 9,
    tidePreference: "mid",
    shadowSensitivity: 0.85,
  },
  ventura: {
    id: "ventura",
    breakType: "point",
    idealSwellDegMin: 240,
    idealSwellDegMax: 300,
    amplificationFactor: 1.1,
    minPeriodSec: 9,
    tidePreference: "mid",
    shadowSensitivity: 0.8,
  },
  venice: {
    id: "venice",
    breakType: "beach",
    idealSwellDegMin: 260,
    idealSwellDegMax: 310,
    amplificationFactor: 1.0,
    minPeriodSec: 8,
    tidePreference: "mid",
    shadowSensitivity: 0.7,
  },
  manhattan: {
    id: "manhattan",
    breakType: "beach",
    idealSwellDegMin: 260,
    idealSwellDegMax: 310,
    amplificationFactor: 1.0,
    minPeriodSec: 8,
    tidePreference: "mid",
    shadowSensitivity: 0.7,
  },
  hermosa: {
    id: "hermosa",
    breakType: "beach",
    idealSwellDegMin: 260,
    idealSwellDegMax: 310,
    amplificationFactor: 1.0,
    minPeriodSec: 8,
    tidePreference: "mid",
    shadowSensitivity: 0.7,
  },
  redondo: {
    id: "redondo",
    breakType: "beach",
    idealSwellDegMin: 260,
    idealSwellDegMax: 310,
    amplificationFactor: 1.0,
    minPeriodSec: 8,
    tidePreference: "mid",
    shadowSensitivity: 0.7,
  },
  "palos-verdes": {
    id: "palos-verdes",
    breakType: "point",
    idealSwellDegMin: 240,
    idealSwellDegMax: 300,
    amplificationFactor: 1.08,
    minPeriodSec: 10,
    tidePreference: "mid",
    shadowSensitivity: 0.85,
  },
  huntington: {
    id: "huntington",
    breakType: "beach",
    idealSwellDegMin: 255,
    idealSwellDegMax: 310,
    amplificationFactor: 1.05,
    minPeriodSec: 8,
    tidePreference: "mid",
    shadowSensitivity: 0.72,
  },
  newport: {
    id: "newport",
    breakType: "beach",
    idealSwellDegMin: 200,
    idealSwellDegMax: 280,
    amplificationFactor: 1.08,
    minPeriodSec: 9,
    tidePreference: "mid",
    shadowSensitivity: 0.78,
  },
  "salt-creek": {
    id: "salt-creek",
    breakType: "reef",
    idealSwellDegMin: 220,
    idealSwellDegMax: 280,
    amplificationFactor: 1.1,
    minPeriodSec: 10,
    tidePreference: "mid",
    shadowSensitivity: 0.85,
  },
  trestles: {
    id: "trestles",
    breakType: "point",
    idealSwellDegMin: 170,
    idealSwellDegMax: 315,
    amplificationFactor: 1.15,
    minPeriodSec: 10,
    tidePreference: "any",
    shadowSensitivity: 0.85,
  },
  "trestles-uppers": {
    id: "trestles-uppers",
    breakType: "point",
    idealSwellDegMin: 170,
    idealSwellDegMax: 315,
    amplificationFactor: 1.12,
    minPeriodSec: 10,
    tidePreference: "mid",
    shadowSensitivity: 0.85,
  },
  "trestles-middles": {
    id: "trestles-middles",
    breakType: "point",
    idealSwellDegMin: 170,
    idealSwellDegMax: 315,
    amplificationFactor: 1.08,
    minPeriodSec: 10,
    tidePreference: "any",
    shadowSensitivity: 0.85,
  },
  tamarack: {
    id: "tamarack",
    breakType: "beach",
    idealSwellDegMin: 180,
    idealSwellDegMax: 310,
    amplificationFactor: 1.05,
    minPeriodSec: 8,
    tidePreference: "mid",
    shadowSensitivity: 0.65,
  },
  oceanside: {
    id: "oceanside",
    breakType: "beach",
    idealSwellDegMin: 180,
    idealSwellDegMax: 310,
    amplificationFactor: 1.05,
    minPeriodSec: 8,
    tidePreference: "mid",
    shadowSensitivity: 0.65,
  },
  "the-rock": {
    id: "the-rock",
    breakType: "beach",
    idealSwellDegMin: 200,
    idealSwellDegMax: 280,
    amplificationFactor: 1.05,
    minPeriodSec: 8,
    tidePreference: "mid",
    shadowSensitivity: 0.7,
  },
  "oceanside-harbor": {
    id: "oceanside-harbor",
    breakType: "jetty",
    idealSwellDegMin: 165,
    idealSwellDegMax: 330,
    amplificationFactor: 1.12,
    minPeriodSec: 8,
    tidePreference: "mid",
    shadowSensitivity: 0.8,
  },
  terramar: {
    id: "terramar",
    breakType: "reef",
    idealSwellDegMin: 270,
    idealSwellDegMax: 310,
    amplificationFactor: 1.1,
    minPeriodSec: 9,
    tidePreference: "mid",
    shadowSensitivity: 0.85,
  },
  "ponto-jetty": {
    id: "ponto-jetty",
    breakType: "jetty",
    idealSwellDegMin: 260,
    idealSwellDegMax: 310,
    amplificationFactor: 1.14,
    minPeriodSec: 8,
    tidePreference: "low",
    shadowSensitivity: 0.78,
  },
  cardiff: {
    id: "cardiff",
    breakType: "reef",
    idealSwellDegMin: 220,
    idealSwellDegMax: 280,
    amplificationFactor: 1.12,
    minPeriodSec: 10,
    tidePreference: "mid",
    shadowSensitivity: 0.88,
  },
  "seaside-reef": {
    id: "seaside-reef",
    breakType: "reef",
    idealSwellDegMin: 220,
    idealSwellDegMax: 280,
    amplificationFactor: 1.1,
    minPeriodSec: 11,
    tidePreference: "mid",
    shadowSensitivity: 0.9,
  },
  "del-mar": {
    id: "del-mar",
    breakType: "beach",
    idealSwellDegMin: 260,
    idealSwellDegMax: 310,
    amplificationFactor: 1.0,
    minPeriodSec: 8,
    tidePreference: "mid",
    shadowSensitivity: 0.72,
  },
  "del-mar-jetty": {
    id: "del-mar-jetty",
    breakType: "jetty",
    idealSwellDegMin: 260,
    idealSwellDegMax: 310,
    amplificationFactor: 1.13,
    minPeriodSec: 8,
    tidePreference: "mid",
    shadowSensitivity: 0.8,
  },
  "blacks-beach": {
    id: "blacks-beach",
    breakType: "beach",
    idealSwellDegMin: 180,
    idealSwellDegMax: 320,
    amplificationFactor: 1.2,
    minPeriodSec: 10,
    tidePreference: "mid",
    shadowSensitivity: 0.75,
  },
  windansea: {
    id: "windansea",
    breakType: "reef",
    idealSwellDegMin: 200,
    idealSwellDegMax: 315,
    amplificationFactor: 1.12,
    minPeriodSec: 10,
    tidePreference: "mid",
    shadowSensitivity: 0.85,
  },
  "scripps-pier": {
    id: "scripps-pier",
    breakType: "beach",
    idealSwellDegMin: 200,
    idealSwellDegMax: 310,
    amplificationFactor: 1.02,
    minPeriodSec: 8,
    tidePreference: "mid",
    shadowSensitivity: 0.72,
  },
  grandview: {
    id: "grandview",
    breakType: "reef",
    idealSwellDegMin: 220,
    idealSwellDegMax: 280,
    amplificationFactor: 1.08,
    minPeriodSec: 9,
    tidePreference: "mid",
    shadowSensitivity: 0.85,
  },
  beacons: {
    id: "beacons",
    breakType: "reef",
    idealSwellDegMin: 220,
    idealSwellDegMax: 280,
    amplificationFactor: 1.08,
    minPeriodSec: 9,
    tidePreference: "mid",
    shadowSensitivity: 0.85,
  },
  "d-street": {
    id: "d-street",
    breakType: "beach",
    idealSwellDegMin: 260,
    idealSwellDegMax: 310,
    amplificationFactor: 1.0,
    minPeriodSec: 8,
    tidePreference: "mid",
    shadowSensitivity: 0.72,
  },
  swamis: {
    id: "swamis",
    breakType: "point",
    idealSwellDegMin: 260,
    idealSwellDegMax: 310,
    amplificationFactor: 1.14,
    minPeriodSec: 10,
    tidePreference: "mid",
    shadowSensitivity: 0.85,
  },
  "pacific-beach": {
    id: "pacific-beach",
    breakType: "beach",
    idealSwellDegMin: 260,
    idealSwellDegMax: 310,
    amplificationFactor: 1.0,
    minPeriodSec: 8,
    tidePreference: "mid",
    shadowSensitivity: 0.7,
  },
  "mission-jetty": {
    id: "mission-jetty",
    breakType: "jetty",
    idealSwellDegMin: 260,
    idealSwellDegMax: 310,
    amplificationFactor: 1.12,
    minPeriodSec: 8,
    tidePreference: "low",
    shadowSensitivity: 0.78,
  },
  "ocean-beach": {
    id: "ocean-beach",
    breakType: "beach",
    idealSwellDegMin: 260,
    idealSwellDegMax: 310,
    amplificationFactor: 1.0,
    minPeriodSec: 8,
    tidePreference: "mid",
    shadowSensitivity: 0.7,
  },
};

export function getSpotProfile(spotId: string): SpotProfile {
  const resolved = SPOT_PROFILE_ALIASES[spotId] ?? spotId;
  const fromSpec = profileFromSpec(resolved);
  if (fromSpec) return fromSpec;
  return SPOT_PROFILES[resolved] ?? { ...DEFAULT_PROFILE, id: resolved };
}
