import type { BoardModel } from "../types";
import { defineModel, T, WAVE } from "../helpers";

export const ALBUM_MODELS: BoardModel[] = [
  defineModel({
    id: "album-midnight-special",
    brand: "Album Surfboards",
    shaper: "Album Surfboards",
    model: "Midnight Special",
    aliases: ["midnight special", "album midnight special"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 5.75,
    volumeBase: 25,
    volumePerFt: 1.0,
    waveRange: WAVE.smallMed,
    traits: T.grovelHybrid,
    shaperNotes:
      "A wide, flat groveler with a quad setup for speed in small-to-medium surf. Album's go-to shape for generating planing speed in average beach breaks.",
    feelSummary:
      "Fast quad groveler — wide and loose in average surf.",
  }),
  defineModel({
    id: "album-doomba",
    brand: "Album Surfboards",
    shaper: "Album Surfboards",
    model: "Doomba",
    aliases: ["doomba", "album doomba"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 5.5,
    volumeBase: 24,
    volumePerFt: 1.1,
    waveRange: WAVE.grovel,
    traits: {
      speed: 9,
      pivot: 8,
      drive: 5,
      paddle: 8,
      hold: 4,
      grovel: 9,
      rail: 5,
    },
    shaperNotes:
      "An ultra-wide, flat grovel board built for the weakest surf. Designed to stay on top of mush and generate speed through dead-flat sections.",
    feelSummary:
      "Ultra-wide mush specialist — maximum planing in gutless surf.",
  }),
  defineModel({
    id: "album-escalator",
    brand: "Album Surfboards",
    shaper: "Album Surfboards",
    model: "Escalator",
    aliases: ["escalator", "album escalator"],
    type: "hybrid",
    finSetup: "thruster",
    defaultLengthFt: 6.0,
    volumeBase: 28,
    volumePerFt: 0.85,
    waveRange: WAVE.daily,
    traits: T.dailyHybrid,
    shaperNotes:
      "A user-friendly hybrid with extra volume for easy wave catching. Designed as a step-up from a groveler for surfers wanting more range in medium surf.",
    feelSummary:
      "Easy-paddling daily hybrid — forgiving with performance potential.",
  }),
  defineModel({
    id: "album-disruption",
    brand: "Album Surfboards",
    shaper: "Album Surfboards",
    model: "Disruption",
    aliases: ["disruption", "album disruption"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 5.67,
    volumeBase: 24,
    volumePerFt: 1.05,
    waveRange: WAVE.smallMed,
    traits: {
      speed: 8,
      pivot: 8,
      drive: 6,
      paddle: 7,
      hold: 5,
      grovel: 8,
      rail: 6,
    },
    shaperNotes:
      "An alternative small-wave design with an unconventional outline for progressive surfing. Built for riders who want speed and release in average conditions.",
    feelSummary:
      "Progressive quad hybrid — unconventional speed and flow.",
  }),
  defineModel({
    id: "album-sabbath",
    brand: "Album Surfboards",
    shaper: "Album Surfboards",
    model: "Sabbath",
    aliases: ["sabbath", "album sabbath"],
    type: "fish",
    finSetup: "twin",
    defaultLengthFt: 5.5,
    volumeBase: 23,
    volumePerFt: 1.1,
    waveRange: WAVE.grovel,
    traits: T.grovelFish,
    shaperNotes:
      "A wide, flat twin-keel fish for maximum glide in weak surf. Album's take on a classic fish with modern rails for a livelier feel.",
    feelSummary:
      "Glide-heavy twin fish — classic speed with modern looseness.",
  }),
  defineModel({
    id: "album-modus",
    brand: "Album Surfboards",
    shaper: "Album Surfboards",
    model: "Modus",
    aliases: ["modus", "album modus"],
    type: "shortboard",
    finSetup: "thruster",
    defaultLengthFt: 5.9,
    volumeBase: 25,
    volumePerFt: 1.0,
    waveRange: WAVE.performance,
    traits: T.hpShort,
    shaperNotes:
      "A high-performance shortboard with a refined outline for clean, punchy surf. Built for tight pocket turns and confident rail engagement.",
    feelSummary:
      "Clean-surf performance stick — snappy and rail-driven.",
  }),
  defineModel({
    id: "album-ledge",
    brand: "Album Surfboards",
    shaper: "Album Surfboards",
    model: "Ledge",
    aliases: ["ledge", "album ledge"],
    type: "hybrid",
    finSetup: "thruster",
    defaultLengthFt: 6.0,
    volumeBase: 27,
    volumePerFt: 0.9,
    waveRange: WAVE.daily,
    traits: T.fun,
    shaperNotes:
      "A mellow, easy-riding hybrid for casual sessions and softer waves. Extra volume and a relaxed rocker make it approachable for a wide range of surfers.",
    feelSummary:
      "Mellow cruiser hybrid — easy waves and relaxed turns.",
  }),
  defineModel({
    id: "album-reef",
    brand: "Album Surfboards",
    shaper: "Album Surfboards",
    model: "Reef",
    aliases: ["reef", "album reef"],
    type: "fish",
    finSetup: "twin",
    defaultLengthFt: 5.67,
    volumeBase: 24,
    volumePerFt: 1.05,
    waveRange: WAVE.smallMed,
    traits: T.perfFish,
    shaperNotes:
      "A modern performance fish with refined rails for tighter turns than a retro twin. Built for speed and maneuverability in small-to-medium surf.",
    feelSummary:
      "Performance fish — speed and glide with modern rail control.",
  }),
];
