import type { BoardModel } from "../types";
import { defineModel, T, WAVE } from "../helpers";

export const BORST_MODELS: BoardModel[] = [
  defineModel({
    id: "borst-magic",
    brand: "Borst Surfboards",
    shaper: "Christian Borst",
    model: "Magic",
    aliases: ["magic", "borst magic"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 5.75,
    volumeBase: 25,
    volumePerFt: 1.0,
    waveRange: WAVE.smallMed,
    traits: T.grovelHybrid,
    shaperNotes:
      "Christian Borst's versatile small-wave design — wide, flat, and quad-driven for speed in average San Diego beach breaks. A go-to groveler with progressive feel.",
    feelSummary:
      "SD grovel hybrid — fast and loose in average beach breaks.",
  }),
  defineModel({
    id: "borst-twin-pin",
    brand: "Borst Surfboards",
    shaper: "Christian Borst",
    model: "Twin Pin",
    aliases: ["twin pin", "twinpin", "borst twin pin"],
    type: "fish",
    finSetup: "twin",
    defaultLengthFt: 5.67,
    volumeBase: 24,
    volumePerFt: 1.05,
    waveRange: WAVE.smallMed,
    traits: T.perfFish,
    shaperNotes:
      "A modern twin-pin fish with refined rails for tighter turns than a classic twin. Built for glide and speed in small-to-medium surf with a lively feel.",
    feelSummary:
      "Modern twin pin — glide and speed with sharper turning arcs.",
  }),
  defineModel({
    id: "borst-mid",
    brand: "Borst Surfboards",
    shaper: "Christian Borst",
    model: "Mid",
    aliases: ["mid", "borst mid", "mid length"],
    type: "funboard",
    finSetup: "2+1",
    defaultLengthFt: 7.0,
    volumeBase: 38,
    volumePerFt: 0.6,
    waveRange: WAVE.daily,
    traits: T.fun,
    shaperNotes:
      "A versatile mid-length with a 2+1 fin setup for easy wave catching and flowing turns. Borst designed it for casual sessions and softer waves.",
    feelSummary:
      "Flowing mid-length — easy paddle and drawn-out turns.",
  }),
  defineModel({
    id: "borst-log",
    brand: "Borst Surfboards",
    shaper: "Christian Borst",
    model: "Log",
    aliases: ["log", "borst log", "longboard"],
    type: "longboard",
    finSetup: "single",
    defaultLengthFt: 9.0,
    volumeBase: 55,
    volumePerFt: 0.5,
    waveRange: WAVE.tiny,
    traits: {
      speed: 5,
      pivot: 5,
      drive: 6,
      paddle: 10,
      hold: 7,
      grovel: 8,
      rail: 4,
    },
    shaperNotes:
      "A classic longboard log for nose riding and mellow trimming. Single fin setup for stability and traditional longboard style in small, soft surf.",
    feelSummary:
      "Classic log — nose rides and mellow trims in small surf.",
  }),
  defineModel({
    id: "borst-hybrid",
    brand: "Borst Surfboards",
    shaper: "Christian Borst",
    model: "Hybrid",
    aliases: ["hybrid", "borst hybrid"],
    type: "hybrid",
    finSetup: "thruster",
    defaultLengthFt: 6.0,
    volumeBase: 28,
    volumePerFt: 0.85,
    waveRange: WAVE.daily,
    traits: T.dailyHybrid,
    shaperNotes:
      "A user-friendly daily-driver hybrid with extra volume for easy paddling. Borst's balanced shape for everyday San Diego conditions.",
    feelSummary:
      "Everyday SD hybrid — easy paddle with responsive turns.",
  }),
  defineModel({
    id: "borst-egg",
    brand: "Borst Surfboards",
    shaper: "Christian Borst",
    model: "Egg",
    aliases: ["egg", "borst egg"],
    type: "funboard",
    finSetup: "2+1",
    defaultLengthFt: 7.2,
    volumeBase: 40,
    volumePerFt: 0.55,
    waveRange: WAVE.daily,
    traits: T.fun,
    shaperNotes:
      "A rounded-egg funboard for easy wave catching and relaxed surfing. High volume and a mellow rocker make it approachable for a wide range of skill levels.",
    feelSummary:
      "Easy egg funboard — high wave count and mellow style.",
  }),
  defineModel({
    id: "borst-step-up",
    brand: "Borst Surfboards",
    shaper: "Christian Borst",
    model: "Step Up",
    aliases: ["step up", "stepup", "borst step up"],
    type: "shortboard",
    finSetup: "thruster",
    defaultLengthFt: 6.2,
    volumeBase: 28,
    volumePerFt: 0.85,
    waveRange: WAVE.stepUp,
    traits: T.stepUp,
    shaperNotes:
      "A step-up shortboard with extra length and refined rails for overhead surf. Built for hold and confidence when San Diego conditions get solid.",
    feelSummary:
      "SD step-up — hold and drive in bigger, more powerful surf.",
  }),
  defineModel({
    id: "borst-fish",
    brand: "Borst Surfboards",
    shaper: "Christian Borst",
    model: "Fish",
    aliases: ["fish", "borst fish"],
    type: "fish",
    finSetup: "twin",
    defaultLengthFt: 5.5,
    volumeBase: 23,
    volumePerFt: 1.1,
    waveRange: WAVE.grovel,
    traits: T.grovelFish,
    shaperNotes:
      "A wide, flat twin-keel fish for generating speed in weak surf. Borst's small-wave specialist for maximum glide and fun in gutless conditions.",
    feelSummary:
      "Grovel fish — maximum glide in the smallest, weakest surf.",
  }),
  defineModel({
    id: "borst-performance",
    brand: "Borst Surfboards",
    shaper: "Christian Borst",
    model: "Performance",
    aliases: ["performance", "borst performance"],
    type: "shortboard",
    finSetup: "thruster",
    defaultLengthFt: 5.9,
    volumeBase: 25,
    volumePerFt: 1.0,
    waveRange: WAVE.performance,
    traits: T.hpShort,
    shaperNotes:
      "A high-performance shortboard with refined rails for clean, punchy surf. Built for tight pocket turns when San Diego conditions have shape and push.",
    feelSummary:
      "Clean-surf shortboard — snappy pocket turns in good waves.",
  }),
];
