import type { BoardModel } from "../types";
import { defineModel, T, WAVE } from "../helpers";

export const CHANNEL_ISLANDS_MODELS: BoardModel[] = [
  defineModel({
    id: "channel-islands-fishbeard",
    brand: "Channel Islands",
    shaper: "Al Merrick / Channel Islands",
    model: "Fishbeard",
    aliases: ["fishbeard", "ci fishbeard", "fish beard"],
    type: "fish",
    finSetup: "twin",
    defaultLengthFt: 5.67,
    volumeBase: 24,
    volumePerFt: 1.1,
    waveRange: WAVE.smallMed,
    traits: {
      speed: 8,
      pivot: 8,
      drive: 6,
      paddle: 7,
      hold: 5,
      grovel: 8,
      rail: 6,
    },
    shaperNotes:
      "CI's modern fish — performance-oriented outline with fish speed and looseness. Merrick lineage: fast down the line with more rail than a retro twin.",
    feelSummary:
      "Performance fish feel — speed and release with tighter turns than a classic twin.",
  }),
  defineModel({
    id: "channel-islands-rocket-wide",
    brand: "Channel Islands",
    shaper: "Al Merrick / Channel Islands",
    model: "Rocket Wide",
    aliases: ["rocket wide", "rocketwide", "ci rocket wide"],
    type: "hybrid",
    finSetup: "thruster",
    defaultLengthFt: 6.0,
    volumeBase: 28,
    volumePerFt: 0.85,
    waveRange: WAVE.daily,
    traits: T.dailyHybrid,
    shaperNotes:
      "A wider, more voluminous version of the Rocket for everyday surf. Extra paddle power and a forgiving outline without losing CI performance heritage.",
    feelSummary:
      "Wide Rocket — easy paddle with CI performance DNA.",
  }),
  defineModel({
    id: "channel-islands-happy-everyday",
    brand: "Channel Islands",
    shaper: "Al Merrick / Channel Islands",
    model: "Happy Everyday",
    aliases: ["happy everyday", "happy everyday", "ci happy everyday"],
    type: "hybrid",
    finSetup: "thruster",
    defaultLengthFt: 6.0,
    volumeBase: 29,
    volumePerFt: 0.8,
    waveRange: WAVE.daily,
    traits: T.fun,
    shaperNotes:
      "A relaxed, user-friendly hybrid designed for everyday sessions. Extra volume and a mellow rocker make it approachable for intermediate surfers.",
    feelSummary:
      "Happy daily driver — forgiving, fun, and easy to ride.",
  }),
  defineModel({
    id: "channel-islands-average-joe",
    brand: "Channel Islands",
    shaper: "Al Merrick / Channel Islands",
    model: "Average Joe",
    aliases: ["average joe", "averagejoe", "ci average joe"],
    type: "hybrid",
    finSetup: "thruster",
    defaultLengthFt: 6.0,
    volumeBase: 30,
    volumePerFt: 0.8,
    waveRange: WAVE.daily,
    traits: {
      speed: 7,
      pivot: 6,
      drive: 6,
      paddle: 9,
      hold: 5,
      grovel: 7,
      rail: 5,
    },
    shaperNotes:
      "CI's benchmark user-friendly board — wide, thick, and easy to paddle for average surfers in average waves. Designed to maximize wave count and fun.",
    feelSummary:
      "Maximum fun for average surfers — easy paddle, forgiving turns.",
  }),
  defineModel({
    id: "channel-islands-fred-rabb",
    brand: "Channel Islands",
    shaper: "Al Merrick / Channel Islands",
    model: "Fred Rabb",
    aliases: ["fred rabb", "fredrabb", "ci fred rabb"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 5.67,
    volumeBase: 25,
    volumePerFt: 1.0,
    waveRange: WAVE.smallMed,
    traits: {
      speed: 8,
      pivot: 8,
      drive: 6,
      paddle: 7,
      hold: 5,
      grovel: 8,
      rail: 6,
    },
    shaperNotes:
      "A wide, flat groveler with a quad setup for speed in small-to-medium surf. CI's answer to soft beach breaks with a skatey, progressive feel.",
    feelSummary:
      "Quad grovel hybrid — fast and loose in average beach breaks.",
  }),
  defineModel({
    id: "channel-islands-two-happy",
    brand: "Channel Islands",
    shaper: "Al Merrick / Channel Islands",
    model: "Two Happy",
    aliases: ["two happy", "twohappy", "ci two happy"],
    type: "fish",
    finSetup: "twin",
    defaultLengthFt: 5.5,
    volumeBase: 24,
    volumePerFt: 1.1,
    waveRange: WAVE.grovel,
    traits: T.grovelFish,
    shaperNotes:
      "A wide, flat twin-keel fish for generating speed in weak surf. Built for maximum glide and fun when conditions are small and soft.",
    feelSummary:
      "Fun twin fish — glide and speed in the smallest surf.",
  }),
  defineModel({
    id: "channel-islands-big-guy",
    brand: "Channel Islands",
    shaper: "Al Merrick / Channel Islands",
    model: "Big Guy",
    aliases: ["big guy", "bigguy", "ci big guy"],
    type: "hybrid",
    finSetup: "thruster",
    defaultLengthFt: 6.4,
    volumeBase: 34,
    volumePerFt: 0.7,
    waveRange: WAVE.daily,
    traits: T.fun,
    shaperNotes:
      "A high-volume hybrid designed for bigger, heavier surfers. Extra width and thickness for easy paddling without sacrificing maneuverability.",
    feelSummary:
      "Big-rider hybrid — high volume with responsive turns.",
  }),
  defineModel({
    id: "channel-islands-pod-mod",
    brand: "Channel Islands",
    shaper: "Al Merrick / Channel Islands",
    model: "Pod Mod",
    aliases: ["pod mod", "podmod", "ci pod mod"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 5.75,
    volumeBase: 26,
    volumePerFt: 0.95,
    waveRange: WAVE.smallMed,
    traits: {
      speed: 8,
      pivot: 7,
      drive: 7,
      paddle: 8,
      hold: 5,
      grovel: 7,
      rail: 6,
    },
    shaperNotes:
      "A modernized Pod with extra volume and a quad option for small-to-medium surf. Blends fish speed with shortboard maneuverability.",
    feelSummary:
      "Modern Pod — fishy speed with quad-driven looseness.",
  }),
  defineModel({
    id: "channel-islands-proton",
    brand: "Channel Islands",
    shaper: "Al Merrick / Channel Islands",
    model: "Proton",
    aliases: ["proton", "ci proton"],
    type: "shortboard",
    finSetup: "thruster",
    defaultLengthFt: 5.9,
    volumeBase: 25,
    volumePerFt: 1.0,
    waveRange: WAVE.performance,
    traits: T.hpShort,
    shaperNotes:
      "A high-performance shortboard with CI's refined rail line for clean, punchy surf. Built for tight pocket turns and confident rail work.",
    feelSummary:
      "CI performance shortboard — snappy and rail-driven in good surf.",
  }),
];
