import type { BoardModel } from "../types";
import { defineModel, T, WAVE } from "../helpers";

export const CHEMISTRY_MODELS: BoardModel[] = [
  defineModel({
    id: "chemistry-msb",
    brand: "Chemistry Surfboards",
    shaper: "Chemistry Surfboards",
    model: "MSB",
    aliases: ["msb", "chemistry msb"],
    type: "shortboard",
    finSetup: "thruster",
    defaultLengthFt: 5.9,
    volumeBase: 25,
    volumePerFt: 1.0,
    waveRange: WAVE.performance,
    traits: T.hpShort,
    shaperNotes:
      "Chemistry's flagship high-performance shortboard — refined rocker and rail line for tight pocket surfing in clean, punchy waves.",
    feelSummary:
      "Pure performance shortboard — snappy and rail-driven in good surf.",
  }),
  defineModel({
    id: "chemistry-lab",
    brand: "Chemistry Surfboards",
    shaper: "Chemistry Surfboards",
    model: "Lab",
    aliases: ["lab", "chemistry lab"],
    type: "hybrid",
    finSetup: "thruster",
    defaultLengthFt: 6.0,
    volumeBase: 28,
    volumePerFt: 0.85,
    waveRange: WAVE.daily,
    traits: T.dailyHybrid,
    shaperNotes:
      "An experimental daily-driver hybrid with extra volume for easy paddling. Designed as a versatile board for a wide range of everyday conditions.",
    feelSummary:
      "Versatile daily hybrid — easy paddle with performance potential.",
  }),
  defineModel({
    id: "chemistry-surf-break",
    brand: "Chemistry Surfboards",
    shaper: "Chemistry Surfboards",
    model: "Surf Break",
    aliases: ["surf break", "surfbreak", "chemistry surf break"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 5.67,
    volumeBase: 25,
    volumePerFt: 1.0,
    waveRange: WAVE.smallMed,
    traits: T.grovelHybrid,
    shaperNotes:
      "A wide, flat groveler with a quad setup for speed in small-to-medium beach breaks. Built to generate planing speed in average Southern California surf.",
    feelSummary:
      "Beach-break groveler — quad speed in average small surf.",
  }),
  defineModel({
    id: "chemistry-litmus",
    brand: "Chemistry Surfboards",
    shaper: "Chemistry Surfboards",
    model: "Litmus",
    aliases: ["litmus", "chemistry litmus"],
    type: "shortboard",
    finSetup: "thruster",
    defaultLengthFt: 6.0,
    volumeBase: 26,
    volumePerFt: 0.95,
    waveRange: WAVE.performance,
    traits: T.driveShort,
    shaperNotes:
      "A drive-focused performance shortboard with a slightly fuller outline for powerful surf. Extra hold and projection through drawn-out turns.",
    feelSummary:
      "Drivey performer — holds and projects in powerful, good surf.",
  }),
  defineModel({
    id: "chemistry-surf-break-xl",
    brand: "Chemistry Surfboards",
    shaper: "Chemistry Surfboards",
    model: "Surf Break XL",
    aliases: ["surf break xl", "surfbreak xl", "chemistry surf break xl"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 6.0,
    volumeBase: 28,
    volumePerFt: 0.85,
    waveRange: WAVE.daily,
    traits: {
      speed: 8,
      pivot: 7,
      drive: 7,
      paddle: 8,
      hold: 5,
      grovel: 7,
      rail: 6,
    },
    shaperNotes:
      "A larger, more voluminous Surf Break for bigger riders or medium surf. Extra width and thickness for easy paddling without losing grovel speed.",
    feelSummary:
      "Stepped-up Surf Break — more volume with quad grovel DNA.",
  }),
  defineModel({
    id: "chemistry-periodic",
    brand: "Chemistry Surfboards",
    shaper: "Chemistry Surfboards",
    model: "Periodic",
    aliases: ["periodic", "chemistry periodic"],
    type: "hybrid",
    finSetup: "thruster",
    defaultLengthFt: 5.75,
    volumeBase: 26,
    volumePerFt: 0.95,
    waveRange: WAVE.smallMed,
    traits: {
      speed: 8,
      pivot: 7,
      drive: 7,
      paddle: 8,
      hold: 5,
      grovel: 7,
      rail: 6,
    },
    shaperNotes:
      "A balanced hybrid with a versatile outline for small-to-medium surf. Enough paddle for average days with enough performance when it cleans up.",
    feelSummary:
      "Balanced everyday hybrid — paddle-friendly with responsive turns.",
  }),
  defineModel({
    id: "chemistry-reaction",
    brand: "Chemistry Surfboards",
    shaper: "Chemistry Surfboards",
    model: "Reaction",
    aliases: ["reaction", "chemistry reaction"],
    type: "shortboard",
    finSetup: "thruster",
    defaultLengthFt: 6.0,
    volumeBase: 27,
    volumePerFt: 0.9,
    waveRange: WAVE.stepUp,
    traits: T.stepUp,
    shaperNotes:
      "A step-up shortboard with extra length and refined rails for overhead surf. Built for hold and drive when conditions push past everyday territory.",
    feelSummary:
      "Overhead step-up — confident hold in bigger, more powerful surf.",
  }),
  defineModel({
    id: "chemistry-compound",
    brand: "Chemistry Surfboards",
    shaper: "Chemistry Surfboards",
    model: "Compound",
    aliases: ["compound", "chemistry compound"],
    type: "fish",
    finSetup: "twin",
    defaultLengthFt: 5.5,
    volumeBase: 23,
    volumePerFt: 1.1,
    waveRange: WAVE.grovel,
    traits: T.grovelFish,
    shaperNotes:
      "A wide, flat twin-keel fish for generating speed in weak surf. Chemistry's small-wave specialist for maximum glide and fun.",
    feelSummary:
      "Glide-heavy twin fish — speed and fun in the weakest surf.",
  }),
  defineModel({
    id: "chemistry-solution",
    brand: "Chemistry Surfboards",
    shaper: "Chemistry Surfboards",
    model: "Solution",
    aliases: ["solution", "chemistry solution"],
    type: "hybrid",
    finSetup: "thruster",
    defaultLengthFt: 6.2,
    volumeBase: 30,
    volumePerFt: 0.8,
    waveRange: WAVE.daily,
    traits: T.fun,
    shaperNotes:
      "A high-volume fun hybrid for casual sessions and softer waves. Extra width and thickness make it approachable for intermediate surfers.",
    feelSummary:
      "Easy fun hybrid — high wave count and mellow turns.",
  }),
];
