import type { BoardModel } from "../types";
import { defineModel, T, WAVE } from "../helpers";

export const CHRISTENSON_MODELS: BoardModel[] = [
  defineModel({
    id: "christenson-tracker",
    brand: "Chris Christenson",
    shaper: "Chris Christenson",
    model: "Tracker",
    aliases: ["tracker", "christenson tracker", "chris christenson tracker"],
    type: "hybrid",
    finSetup: "thruster",
    defaultLengthFt: 6.0,
    volumeBase: 28,
    volumePerFt: 0.85,
    waveRange: WAVE.daily,
    traits: T.dailyHybrid,
    shaperNotes:
      "Chris Christenson's versatile daily-driver hybrid — extra volume and a balanced outline for easy paddling in average surf. A reliable go-to for everyday sessions.",
    feelSummary:
      "Balanced daily hybrid — easy paddle with responsive turns.",
  }),
  defineModel({
    id: "christenson-fisher",
    brand: "Chris Christenson",
    shaper: "Chris Christenson",
    model: "Fisher",
    aliases: ["fisher", "christenson fisher"],
    type: "fish",
    finSetup: "twin",
    defaultLengthFt: 5.67,
    volumeBase: 24,
    volumePerFt: 1.05,
    waveRange: WAVE.smallMed,
    traits: T.perfFish,
    shaperNotes:
      "A modern performance fish with refined rails and a pulled-in tail. Christenson's take on a fish that turns tighter than a retro twin while keeping glide.",
    feelSummary:
      "Performance fish — glide and speed with modern rail control.",
  }),
  defineModel({
    id: "christenson-horizon",
    brand: "Chris Christenson",
    shaper: "Chris Christenson",
    model: "Horizon",
    aliases: ["horizon", "christenson horizon"],
    type: "funboard",
    finSetup: "2+1",
    defaultLengthFt: 7.0,
    volumeBase: 38,
    volumePerFt: 0.6,
    waveRange: WAVE.daily,
    traits: T.fun,
    shaperNotes:
      "A versatile mid-length with a 2+1 fin setup for easy wave catching and flowing turns. Designed for casual sessions and softer waves.",
    feelSummary:
      "Flowing mid-length — easy paddle and drawn-out carves.",
  }),
  defineModel({
    id: "christenson-surf-craft",
    brand: "Chris Christenson",
    shaper: "Chris Christenson",
    model: "Surf Craft",
    aliases: ["surf craft", "surfcraft", "christenson surf craft"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 5.75,
    volumeBase: 26,
    volumePerFt: 0.95,
    waveRange: WAVE.smallMed,
    traits: {
      speed: 8,
      pivot: 8,
      drive: 6,
      paddle: 7,
      hold: 5,
      grovel: 8,
      rail: 6,
    },
    shaperNotes:
      "An alternative small-wave design with a wide outline and quad fins for progressive surfing. Built for speed and release in average beach breaks.",
    feelSummary:
      "Progressive quad hybrid — unconventional speed in average surf.",
  }),
  defineModel({
    id: "christenson-mbi",
    brand: "Chris Christenson",
    shaper: "Chris Christenson",
    model: "MBI",
    aliases: ["mbi", "christenson mbi"],
    type: "shortboard",
    finSetup: "thruster",
    defaultLengthFt: 5.9,
    volumeBase: 25,
    volumePerFt: 1.0,
    waveRange: WAVE.performance,
    traits: T.hpShort,
    shaperNotes:
      "A high-performance shortboard with Christenson's refined rail line for clean, punchy surf. Built for tight pocket turns and confident rail engagement.",
    feelSummary:
      "Clean-surf performer — snappy and rail-driven.",
  }),
  defineModel({
    id: "christenson-cetacean",
    brand: "Chris Christenson",
    shaper: "Chris Christenson",
    model: "Cetacean",
    aliases: ["cetacean", "christenson cetacean"],
    type: "fish",
    finSetup: "twin",
    defaultLengthFt: 5.5,
    volumeBase: 23,
    volumePerFt: 1.1,
    waveRange: WAVE.grovel,
    traits: T.grovelFish,
    shaperNotes:
      "A wide, flat twin-keel fish for generating speed in weak surf. Christenson's small-wave specialist with maximum glide and a lively feel.",
    feelSummary:
      "Glide-heavy twin fish — speed and fun in the weakest surf.",
  }),
  defineModel({
    id: "christenson-ufo",
    brand: "Chris Christenson",
    shaper: "Chris Christenson",
    model: "UFO",
    aliases: ["ufo", "christenson ufo"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 5.5,
    volumeBase: 24,
    volumePerFt: 1.1,
    waveRange: WAVE.grovel,
    traits: T.grovelHybrid,
    shaperNotes:
      "An ultra-wide grovel board with a quad setup for maximum planing speed in marginal surf. Built for the days when nothing else will stay on top of the mush.",
    feelSummary:
      "Ultra-wide groveler — maximum speed in gutless surf.",
  }),
  defineModel({
    id: "christenson-nautilus",
    brand: "Chris Christenson",
    shaper: "Chris Christenson",
    model: "Nautilus",
    aliases: ["nautilus", "christenson nautilus"],
    type: "longboard",
    finSetup: "single",
    defaultLengthFt: 9.2,
    volumeBase: 58,
    volumePerFt: 0.45,
    waveRange: WAVE.tiny,
    traits: {
      speed: 5,
      pivot: 5,
      drive: 6,
      paddle: 10,
      hold: 7,
      grovel: 8,
      rail: 4,
    },
    shaperNotes:
      "A classic longboard log for nose riding and mellow trimming. Single fin setup for stability and traditional longboard style in small, soft surf.",
    feelSummary:
      "Traditional log — nose rides and mellow trims in small surf.",
  }),
  defineModel({
    id: "christenson-rnf",
    brand: "Chris Christenson",
    shaper: "Chris Christenson",
    model: "RNF",
    aliases: ["rnf", "christenson rnf", "ride anything fish"],
    type: "fish",
    finSetup: "twin",
    defaultLengthFt: 5.5,
    volumeBase: 24,
    volumePerFt: 1.1,
    waveRange: WAVE.grovel,
    traits: {
      speed: 8,
      pivot: 7,
      drive: 5,
      paddle: 8,
      hold: 4,
      grovel: 9,
      rail: 5,
    },
    shaperNotes:
      "The Ride Anything Fish — a versatile twin that handles everything from knee-high mush to chest-high beach breaks. Christenson's benchmark small-wave board.",
    feelSummary:
      "Ride-anything fish — versatile glide from mush to chest-high.",
  }),
];
