import type { BoardModel } from "../types";
import { defineModel, T, WAVE } from "../helpers";

export const FIREWIRE_MODELS: BoardModel[] = [
  defineModel({
    id: "firewire-dominator",
    brand: "Firewire",
    shaper: "Firewire / various",
    model: "Dominator",
    aliases: ["dominator", "firewire dominator"],
    type: "hybrid",
    finSetup: "thruster",
    defaultLengthFt: 6.0,
    volumeBase: 28,
    volumePerFt: 0.8,
    waveRange: WAVE.daily,
    traits: T.dailyHybrid,
    shaperNotes:
      "Firewire's benchmark daily driver — extra volume and a forgiving outline for easy paddling in average surf. Designed to catch waves early and turn without demanding perfect technique.",
    feelSummary:
      "Forgiving, high-volume hybrid for everyday sessions.",
  }),
  defineModel({
    id: "firewire-sweet-potato",
    brand: "Firewire",
    shaper: "Firewire / various",
    model: "Sweet Potato",
    aliases: ["sweet potato", "firewire sweet potato"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 5.5,
    volumeBase: 24,
    volumePerFt: 1.1,
    waveRange: WAVE.grovel,
    traits: T.grovelHybrid,
    shaperNotes:
      "A wide, flat groveler built for tiny, weak surf. The Sweet Potato planes early and stays loose through soft sections with a quad setup for quick release.",
    feelSummary:
      "Ultra-wide grovel machine for the smallest, weakest days.",
  }),
  defineModel({
    id: "firewire-baked-potato",
    brand: "Firewire",
    shaper: "Firewire / various",
    model: "Baked Potato",
    aliases: ["baked potato", "firewire baked potato"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 5.67,
    volumeBase: 25,
    volumePerFt: 1.05,
    waveRange: WAVE.smallMed,
    traits: {
      speed: 8,
      pivot: 7,
      drive: 6,
      paddle: 8,
      hold: 5,
      grovel: 8,
      rail: 5,
    },
    shaperNotes:
      "A slightly more refined Potato shape for small-to-medium surf. Still wide and flat but with enough performance to handle a clean 3–4 ft face.",
    feelSummary:
      "Stepped-up Potato — grovel speed with a bit more performance range.",
  }),
  defineModel({
    id: "firewire-vanguard",
    brand: "Firewire",
    shaper: "Firewire / various",
    model: "Vanguard",
    aliases: ["vanguard", "firewire vanguard"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 5.5,
    volumeBase: 23,
    volumePerFt: 1.1,
    waveRange: WAVE.smallMed,
    traits: {
      speed: 8,
      pivot: 8,
      drive: 6,
      paddle: 7,
      hold: 5,
      grovel: 8,
      rail: 6,
    },
    shaperNotes:
      "Tomo-inspired alternative outline with a wide nose and diamond tail for speed and release. Built for progressive surfing in average beach-break conditions.",
    feelSummary:
      "Alternative hybrid — fast, loose, and unconventional in small surf.",
  }),
  defineModel({
    id: "firewire-sci-fi",
    brand: "Firewire",
    shaper: "Firewire / various",
    model: "Sci-Fi",
    aliases: ["sci-fi", "scifi", "firewire sci-fi"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 5.67,
    volumeBase: 24,
    volumePerFt: 1.05,
    waveRange: WAVE.smallMed,
    traits: {
      speed: 9,
      pivot: 8,
      drive: 6,
      paddle: 7,
      hold: 5,
      grovel: 8,
      rail: 6,
    },
    shaperNotes:
      "Daniel Thomson's futuristic small-wave design with a wide, parallel outline and quad fins. Generates speed through flat sections with a skatey, progressive feel.",
    feelSummary:
      "Futuristic quad hybrid — speed and release in average surf.",
  }),
  defineModel({
    id: "firewire-seaside",
    brand: "Firewire",
    shaper: "Firewire / various",
    model: "Seaside",
    aliases: ["seaside", "firewire seaside"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 5.67,
    volumeBase: 24,
    volumePerFt: 1.05,
    waveRange: WAVE.smallMed,
    traits: {
      speed: 8,
      pivot: 8,
      drive: 6,
      paddle: 7,
      hold: 5,
      grovel: 8,
      rail: 6,
    },
    shaperNotes:
      "Rob Machado's small-wave shape — wide, flat, and quad-driven for soft beach breaks. Blends fish glide with shortboard maneuverability for everyday sessions.",
    feelSummary:
      "Machado's daily groveler — fishy speed with quad looseness.",
  }),
  defineModel({
    id: "firewire-omni",
    brand: "Firewire",
    shaper: "Firewire / various",
    model: "Omni",
    aliases: ["omni", "firewire omni"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 5.5,
    volumeBase: 23,
    volumePerFt: 1.1,
    waveRange: WAVE.grovel,
    traits: T.grovelHybrid,
    shaperNotes:
      "A versatile small-wave board with a wide outline and flat rocker for planing speed. The Omni handles everything from knee-high mush to chest-high beach breaks.",
    feelSummary:
      "All-around grovel hybrid — wide, fast, and easy to ride.",
  }),
  defineModel({
    id: "firewire-spitfire",
    brand: "Firewire",
    shaper: "Firewire / various",
    model: "Spitfire",
    aliases: ["spitfire", "firewire spitfire"],
    type: "shortboard",
    finSetup: "thruster",
    defaultLengthFt: 5.9,
    volumeBase: 25,
    volumePerFt: 1.0,
    waveRange: WAVE.performance,
    traits: T.hpShort,
    shaperNotes:
      "A high-performance shortboard with a refined outline for good-quality surf. Built for tight pocket surfing and confident rail work in clean 3–6 ft conditions.",
    feelSummary:
      "Clean-surf performance shortboard — snappy and rail-driven.",
  }),
  defineModel({
    id: "firewire-sunday",
    brand: "Firewire",
    shaper: "Firewire / various",
    model: "Sunday",
    aliases: ["sunday", "firewire sunday"],
    type: "hybrid",
    finSetup: "thruster",
    defaultLengthFt: 6.0,
    volumeBase: 28,
    volumePerFt: 0.85,
    waveRange: WAVE.daily,
    traits: T.fun,
    shaperNotes:
      "A relaxed, easy-riding hybrid for casual weekend sessions. Extra volume and a mellow rocker make it approachable for intermediate surfers in average conditions.",
    feelSummary:
      "Laid-back weekend hybrid — easy paddle and forgiving turns.",
  }),
  defineModel({
    id: "firewire-tunabit",
    brand: "Firewire",
    shaper: "Firewire / various",
    model: "Tunabit",
    aliases: ["tunabit", "tt", "firewire tunabit", "firewire tt"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 5.75,
    volumeBase: 25,
    volumePerFt: 1.0,
    waveRange: WAVE.smallMed,
    traits: {
      speed: 8,
      pivot: 8,
      drive: 6,
      paddle: 7,
      hold: 5,
      grovel: 8,
      rail: 6,
    },
    shaperNotes:
      "An alternative small-wave design with a wide tail and quad setup for progressive surfing. Built for riders who want speed and release without a traditional shortboard outline.",
    feelSummary:
      "Progressive small-wave quad — unconventional speed and flow.",
  }),
];
