import type { BoardModel } from "../types";
import { defineModel, T, WAVE } from "../helpers";

export const HAYDEN_SHAPES_MODELS: BoardModel[] = [
  defineModel({
    id: "hayden-shapes-hypto-krypto",
    brand: "Hayden Shapes",
    shaper: "Hayden Cox / Hayden Shapes",
    model: "Hypto Krypto",
    aliases: ["hypto krypto", "hyptokrypto", "hypto", "hayden shapes hypto krypto"],
    type: "hybrid",
    finSetup: "thruster",
    defaultLengthFt: 6.0,
    volumeBase: 30,
    volumePerFt: 0.8,
    waveRange: WAVE.daily,
    traits: {
      speed: 8,
      pivot: 7,
      drive: 7,
      paddle: 9,
      hold: 6,
      grovel: 7,
      rail: 6,
    },
    shaperNotes:
      "Hayden Cox's one-board quiver killer — a versatile hybrid outline that paddles like a funboard and performs like a shortboard. Designed to handle everything from 2–8 ft.",
    feelSummary:
      "True one-board quiver — paddles easy, performs when it gets good.",
  }),
  defineModel({
    id: "hayden-shapes-holy-grail",
    brand: "Hayden Shapes",
    shaper: "Hayden Cox / Hayden Shapes",
    model: "Holy Grail",
    aliases: ["holy grail", "holygrail", "hayden shapes holy grail"],
    type: "shortboard",
    finSetup: "thruster",
    defaultLengthFt: 5.9,
    volumeBase: 25,
    volumePerFt: 1.0,
    waveRange: WAVE.performance,
    traits: T.hpShort,
    shaperNotes:
      "A high-performance shortboard with Hayden's refined rail line for clean, punchy surf. Built for tight pocket turns and confident rail work in good-quality waves.",
    feelSummary:
      "Clean-surf performer — snappy pocket turns and rail control.",
  }),
  defineModel({
    id: "hayden-shapes-white-hawk",
    brand: "Hayden Shapes",
    shaper: "Hayden Cox / Hayden Shapes",
    model: "White Hawk",
    aliases: ["white hawk", "whitehawk", "hayden shapes white hawk"],
    type: "shortboard",
    finSetup: "thruster",
    defaultLengthFt: 6.0,
    volumeBase: 26,
    volumePerFt: 0.95,
    waveRange: WAVE.performance,
    traits: T.driveShort,
    shaperNotes:
      "A drive-focused performance shortboard with a slightly fuller outline for powerful surf. Extra hold and projection through drawn-out turns in good waves.",
    feelSummary:
      "Drivey performer — holds and projects in powerful surf.",
  }),
  defineModel({
    id: "hayden-shapes-phish",
    brand: "Hayden Shapes",
    shaper: "Hayden Cox / Hayden Shapes",
    model: "PHISH",
    aliases: ["phish", "hayden shapes phish"],
    type: "fish",
    finSetup: "twin",
    defaultLengthFt: 5.5,
    volumeBase: 23,
    volumePerFt: 1.1,
    waveRange: WAVE.grovel,
    traits: T.grovelFish,
    shaperNotes:
      "A wide, flat twin-keel fish for generating speed in weak surf. Hayden's small-wave specialist with maximum glide and a lively, skatey feel.",
    feelSummary:
      "Glide-heavy twin fish — speed and fun in the weakest surf.",
  }),
  defineModel({
    id: "hayden-shapes-love-buzz",
    brand: "Hayden Shapes",
    shaper: "Hayden Cox / Hayden Shapes",
    model: "Love Buzz",
    aliases: ["love buzz", "lovebuzz", "hayden shapes love buzz"],
    type: "hybrid",
    finSetup: "thruster",
    defaultLengthFt: 5.67,
    volumeBase: 26,
    volumePerFt: 0.95,
    waveRange: WAVE.smallMed,
    traits: {
      speed: 8,
      pivot: 7,
      drive: 7,
      paddle: 8,
      hold: 5,
      grovel: 7,
      rail: 6,
    },
    shaperNotes:
      "A user-friendly hybrid with extra volume for easy paddling in small-to-medium surf. Designed as a step-down from a performance shortboard for everyday sessions.",
    feelSummary:
      "Easy-paddling hybrid — forgiving with performance heritage.",
  }),
  defineModel({
    id: "hayden-shapes-hypto-krypto-fl",
    brand: "Hayden Shapes",
    shaper: "Hayden Cox / Hayden Shapes",
    model: "Hypto Krypto FL",
    aliases: ["hypto krypto fl", "hypto fl", "hypto krypto future flex", "hayden shapes hypto krypto fl"],
    type: "hybrid",
    finSetup: "thruster",
    defaultLengthFt: 6.0,
    volumeBase: 30,
    volumePerFt: 0.8,
    waveRange: WAVE.daily,
    traits: {
      speed: 8,
      pivot: 7,
      drive: 7,
      paddle: 9,
      hold: 6,
      grovel: 7,
      rail: 6,
    },
    shaperNotes:
      "The Future Flex construction version of the Hypto Krypto — same versatile one-board outline with a livelier, more responsive feel underfoot.",
    feelSummary:
      "Lively Hypto Krypto — same versatility with a snappier flex pattern.",
  }),
  defineModel({
    id: "hayden-shapes-planche",
    brand: "Hayden Shapes",
    shaper: "Hayden Cox / Hayden Shapes",
    model: "Planche",
    aliases: ["planche", "hayden shapes planche"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 5.67,
    volumeBase: 25,
    volumePerFt: 1.0,
    waveRange: WAVE.smallMed,
    traits: T.grovelHybrid,
    shaperNotes:
      "A wide, flat groveler with a quad setup for speed in small-to-medium surf. Hayden's alternative small-wave design for progressive beach-break surfing.",
    feelSummary:
      "Quad grovel hybrid — wide and fast in average beach breaks.",
  }),
  defineModel({
    id: "hayden-shapes-untitled",
    brand: "Hayden Shapes",
    shaper: "Hayden Cox / Hayden Shapes",
    model: "Untitled",
    aliases: ["untitled", "hayden shapes untitled"],
    type: "shortboard",
    finSetup: "thruster",
    defaultLengthFt: 6.0,
    volumeBase: 27,
    volumePerFt: 0.9,
    waveRange: WAVE.stepUp,
    traits: T.stepUp,
    shaperNotes:
      "A step-up shortboard with extra length and refined rails for overhead surf. Built for hold and confidence when conditions push past everyday territory.",
    feelSummary:
      "Overhead step-up — hold and drive in bigger, more powerful surf.",
  }),
  defineModel({
    id: "hayden-shapes-shred-sled",
    brand: "Hayden Shapes",
    shaper: "Hayden Cox / Hayden Shapes",
    model: "Shred Sled",
    aliases: ["shred sled", "shredsled", "hayden shapes shred sled"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 5.5,
    volumeBase: 24,
    volumePerFt: 1.1,
    waveRange: WAVE.grovel,
    traits: {
      speed: 9,
      pivot: 8,
      drive: 5,
      paddle: 8,
      hold: 4,
      grovel: 9,
      rail: 5,
    },
    shaperNotes:
      "An ultra-wide grovel board built for maximum fun in the smallest, weakest surf. Flat rocker and a quad setup keep it planing when nothing else will.",
    feelSummary:
      "Party-wave groveler — maximum fun in the weakest surf.",
  }),
];
