import type { BoardModel } from "../types";
import { defineModel, T, WAVE } from "../helpers";

export const JS_INDUSTRIES_MODELS: BoardModel[] = [
  defineModel({
    id: "js-xero-gravity",
    brand: "JS Industries",
    shaper: "Jason Stevens / JS Industries",
    model: "Xero Gravity",
    aliases: ["xero gravity", "js xero gravity", "js xero"],
    type: "shortboard",
    finSetup: "thruster",
    defaultLengthFt: 6.0,
    volumeBase: 27,
    volumePerFt: 0.85,
    waveRange: WAVE.performance,
    traits: T.driveShort,
    shaperNotes:
      "Jason Stevens designed the Xero Gravity as a high-performance shortboard with extra drive and hold — a slightly fuller outline and rocker for powerful, good-quality surf.",
    feelSummary:
      "Drivey, high-performance shortboard for good waves — holds a line in the pocket with confidence.",
  }),
  defineModel({
    id: "js-monsta-6",
    brand: "JS Industries",
    shaper: "Jason Stevens / JS Industries",
    model: "Monsta 6",
    aliases: ["monsta 6", "monsta6", "js monsta 6"],
    type: "shortboard",
    finSetup: "thruster",
    defaultLengthFt: 5.9,
    volumeBase: 25,
    volumePerFt: 1.0,
    waveRange: WAVE.performance,
    traits: T.hpShort,
    shaperNotes:
      "JS's flagship high-performance shortboard — refined rocker and rail line for tight pocket surfing. The go-to contest shape for powerful, good-quality waves.",
    feelSummary:
      "Pure performance shortboard — snappy, rail-driven, contest-ready.",
  }),
  defineModel({
    id: "js-monsta-10",
    brand: "JS Industries",
    shaper: "Jason Stevens / JS Industries",
    model: "Monsta 10",
    aliases: ["monsta 10", "monsta10", "js monsta 10"],
    type: "shortboard",
    finSetup: "thruster",
    defaultLengthFt: 6.0,
    volumeBase: 26,
    volumePerFt: 0.95,
    waveRange: WAVE.performance,
    traits: {
      speed: 7,
      pivot: 7,
      drive: 9,
      paddle: 6,
      hold: 9,
      grovel: 3,
      rail: 9,
    },
    shaperNotes:
      "An evolution of the Monsta with more volume and a slightly wider outline for bigger, more powerful surf. Extra drive and hold for confident surfing in overhead conditions.",
    feelSummary:
      "Stepped-up Monsta — more volume and hold for powerful surf.",
  }),
  defineModel({
    id: "js-blak-baron",
    brand: "JS Industries",
    shaper: "Jason Stevens / JS Industries",
    model: "Blak Baron",
    aliases: ["blak baron", "black baron", "js blak baron"],
    type: "hybrid",
    finSetup: "thruster",
    defaultLengthFt: 6.0,
    volumeBase: 28,
    volumePerFt: 0.85,
    waveRange: WAVE.daily,
    traits: T.dailyHybrid,
    shaperNotes:
      "A user-friendly hybrid with extra width and volume for easy paddling. Designed as a step-down from a performance shortboard for average everyday conditions.",
    feelSummary:
      "Forgiving daily driver — easy paddle with performance heritage.",
  }),
  defineModel({
    id: "js-air-17",
    brand: "JS Industries",
    shaper: "Jason Stevens / JS Industries",
    model: "Air 17",
    aliases: ["air 17", "air17", "js air 17"],
    type: "hybrid",
    finSetup: "thruster",
    defaultLengthFt: 5.67,
    volumeBase: 26,
    volumePerFt: 0.95,
    waveRange: WAVE.smallMed,
    traits: {
      speed: 8,
      pivot: 7,
      drive: 7,
      paddle: 8,
      hold: 5,
      grovel: 7,
      rail: 6,
    },
    shaperNotes:
      "A lightweight, high-volume hybrid built for small-to-medium surf. Extra foam distribution keeps it lively and responsive without sacrificing paddle power.",
    feelSummary:
      "Light, lively hybrid for average surf — paddle-friendly with snap.",
  }),
  defineModel({
    id: "js-big-baron",
    brand: "JS Industries",
    shaper: "Jason Stevens / JS Industries",
    model: "Big Baron",
    aliases: ["big baron", "js big baron"],
    type: "hybrid",
    finSetup: "thruster",
    defaultLengthFt: 6.2,
    volumeBase: 30,
    volumePerFt: 0.8,
    waveRange: WAVE.daily,
    traits: T.fun,
    shaperNotes:
      "A larger, more voluminous version of the Baron line for heavier surfers or bigger average surf. Built for easy wave catching and relaxed, flowing turns.",
    feelSummary:
      "High-volume cruiser — easy waves and flowing turns for bigger riders.",
  }),
  defineModel({
    id: "js-ponytail",
    brand: "JS Industries",
    shaper: "Jason Stevens / JS Industries",
    model: "Ponytail",
    aliases: ["ponytail", "js ponytail"],
    type: "fish",
    finSetup: "twin",
    defaultLengthFt: 5.5,
    volumeBase: 23,
    volumePerFt: 1.1,
    waveRange: WAVE.grovel,
    traits: T.grovelFish,
    shaperNotes:
      "A modern twin-keel fish with a pulled-in tail for tighter turns than a classic fish. Built for generating speed and glide in weak, small surf.",
    feelSummary:
      "Modern performance fish — glide and speed with tighter arcs.",
  }),
  defineModel({
    id: "js-the-bastard",
    brand: "JS Industries",
    shaper: "Jason Stevens / JS Industries",
    model: "The Bastard",
    aliases: ["the bastard", "bastard", "js bastard"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 5.75,
    volumeBase: 25,
    volumePerFt: 1.0,
    waveRange: WAVE.smallMed,
    traits: {
      speed: 8,
      pivot: 8,
      drive: 6,
      paddle: 7,
      hold: 5,
      grovel: 8,
      rail: 6,
    },
    shaperNotes:
      "An unconventional hybrid with a wide, flat outline and quad fins for small-wave performance. Designed for progressive surfing when conditions are average at best.",
    feelSummary:
      "Unconventional quad hybrid — loose, fast, and fun in average surf.",
  }),
  defineModel({
    id: "js-black-eagle",
    brand: "JS Industries",
    shaper: "Jason Stevens / JS Industries",
    model: "Black Eagle",
    aliases: ["black eagle", "js black eagle"],
    type: "shortboard",
    finSetup: "thruster",
    defaultLengthFt: 6.1,
    volumeBase: 27,
    volumePerFt: 0.9,
    waveRange: WAVE.stepUp,
    traits: T.stepUp,
    shaperNotes:
      "A step-up shortboard with extra length and refined rails for overhead surf. Built for hold and drive when conditions push past everyday shortboard territory.",
    feelSummary:
      "Confident step-up — hold and drive in overhead, powerful surf.",
  }),
];
