import type { BoardModel } from "../types";
import { defineModel, T, WAVE } from "../helpers";

export const LOST_MODELS: BoardModel[] = [
  defineModel({
    id: "lost-mini-driver",
    brand: "Lost Surfboards",
    shaper: "Matt Biolos / Lost",
    model: "Mini Driver",
    aliases: ["mini driver", "minidriver", "lost mini driver"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 5.67,
    volumeBase: 26,
    volumePerFt: 0.95,
    waveRange: WAVE.smallMed,
    traits: {
      speed: 8,
      pivot: 7,
      drive: 7,
      paddle: 8,
      hold: 5,
      grovel: 8,
      rail: 6,
    },
    shaperNotes:
      "Matt Biolos designed the Mini Driver as a user-friendly step-down — extra volume and width for easy paddling, with a performance outline that still turns tight in small-to-medium surf.",
    feelSummary:
      "Easy paddle and forgiving lines with enough performance for everyday sessions.",
  }),
  defineModel({
    id: "lost-puddle-fish",
    brand: "Lost Surfboards",
    shaper: "Matt Biolos / Lost",
    model: "Puddle Fish",
    aliases: ["puddle fish", "puddlefish", "lost puddle fish"],
    type: "fish",
    finSetup: "twin",
    defaultLengthFt: 5.5,
    volumeBase: 22.5,
    volumePerFt: 1.0,
    waveRange: WAVE.grovel,
    traits: {
      speed: 8,
      pivot: 7,
      drive: 5,
      paddle: 9,
      hold: 3,
      grovel: 10,
      rail: 4,
    },
    shaperNotes:
      "A grovel-machine fish — wide, flat, and twin-keeled for maximum glide in tiny, weak surf. Biolos built it for the slop days when shortboards sit on the rack.",
    feelSummary:
      "Maximum glide and paddle in the smallest, weakest surf.",
  }),
  defineModel({
    id: "lost-rad-ripper",
    brand: "Lost Surfboards",
    shaper: "Matt Biolos / Lost",
    model: "Rad Ripper",
    aliases: ["rad ripper", "radripper", "lost rad ripper"],
    type: "hybrid",
    finSetup: "thruster",
    defaultLengthFt: 5.67,
    volumeBase: 25,
    volumePerFt: 1.0,
    waveRange: WAVE.smallMed,
    traits: {
      speed: 8,
      pivot: 8,
      drive: 6,
      paddle: 7,
      hold: 5,
      grovel: 8,
      rail: 6,
    },
    shaperNotes:
      "A wide, flat groveler with a performance attitude for small-to-medium surf. Biolos designed it to rip in average beach breaks with a skatey, progressive feel.",
    feelSummary:
      "Skatey grovel hybrid — fast and loose in average beach breaks.",
  }),
  defineModel({
    id: "lost-pj",
    brand: "Lost Surfboards",
    shaper: "Matt Biolos / Lost",
    model: "PJ",
    aliases: ["pj", "lost pj", "pj lost"],
    type: "shortboard",
    finSetup: "thruster",
    defaultLengthFt: 5.9,
    volumeBase: 25,
    volumePerFt: 1.0,
    waveRange: WAVE.performance,
    traits: T.hpShort,
    shaperNotes:
      "Parkinson-inspired high-performance shortboard with a refined outline for clean, punchy surf. Tight radius turns and strong rail engagement in good-quality waves.",
    feelSummary:
      "High-performance shortboard — snappy pocket surfing in clean surf.",
  }),
  defineModel({
    id: "lost-sub-scorcher",
    brand: "Lost Surfboards",
    shaper: "Matt Biolos / Lost",
    model: "Sub Scorcher",
    aliases: ["sub scorcher", "subscorcher", "lost sub scorcher"],
    type: "shortboard",
    finSetup: "thruster",
    defaultLengthFt: 6.0,
    volumeBase: 26,
    volumePerFt: 0.95,
    waveRange: WAVE.performance,
    traits: T.driveShort,
    shaperNotes:
      "A slightly fuller performance shortboard with extra paddle for good-quality surf. Designed to handle speed and power without sacrificing maneuverability.",
    feelSummary:
      "Drivey performance shortboard — paddle-friendly with contest feel.",
  }),
  defineModel({
    id: "lost-quiver-killer",
    brand: "Lost Surfboards",
    shaper: "Matt Biolos / Lost",
    model: "Quiver Killer",
    aliases: ["quiver killer", "quiverkiller", "lost quiver killer"],
    type: "hybrid",
    finSetup: "thruster",
    defaultLengthFt: 6.0,
    volumeBase: 28,
    volumePerFt: 0.85,
    waveRange: WAVE.daily,
    traits: T.dailyHybrid,
    shaperNotes:
      "Biolos's one-board answer for most conditions — enough volume for easy paddling with a performance outline that handles a wide range of wave sizes.",
    feelSummary:
      "True quiver killer — one board for most everyday conditions.",
  }),
  defineModel({
    id: "lost-lazy-rider",
    brand: "Lost Surfboards",
    shaper: "Matt Biolos / Lost",
    model: "Lazy Rider",
    aliases: ["lazy rider", "lazyrider", "lost lazy rider"],
    type: "funboard",
    finSetup: "thruster",
    defaultLengthFt: 6.5,
    volumeBase: 32,
    volumePerFt: 0.75,
    waveRange: WAVE.daily,
    traits: T.fun,
    shaperNotes:
      "A relaxed, high-volume funboard for casual sessions and softer waves. Extra width and thickness make it approachable for intermediate surfers.",
    feelSummary:
      "Laid-back funboard — easy waves and mellow turns.",
  }),
  defineModel({
    id: "lost-party-tray",
    brand: "Lost Surfboards",
    shaper: "Matt Biolos / Lost",
    model: "Party Tray",
    aliases: ["party tray", "partytray", "lost party tray"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 5.5,
    volumeBase: 24,
    volumePerFt: 1.1,
    waveRange: WAVE.grovel,
    traits: T.grovelHybrid,
    shaperNotes:
      "An ultra-wide grovel board built for the smallest, weakest surf. Flat rocker and a quad setup keep it planing when nothing else will.",
    feelSummary:
      "Party-wave groveler — maximum fun in the weakest surf.",
  }),
  defineModel({
    id: "lost-pelagic",
    brand: "Lost Surfboards",
    shaper: "Matt Biolos / Lost",
    model: "Pelagic",
    aliases: ["pelagic", "lost pelagic"],
    type: "fish",
    finSetup: "twin",
    defaultLengthFt: 5.67,
    volumeBase: 24,
    volumePerFt: 1.05,
    waveRange: WAVE.smallMed,
    traits: T.perfFish,
    shaperNotes:
      "A modern performance fish with a pulled-in tail and refined rails. Faster and more maneuverable than a retro twin while keeping fish glide and speed.",
    feelSummary:
      "Performance fish — glide and speed with tighter turning arcs.",
  }),
  defineModel({
    id: "lost-round-pin-pj",
    brand: "Lost Surfboards",
    shaper: "Matt Biolos / Lost",
    model: "Round Pin PJ",
    aliases: ["round pin pj", "roundpin pj", "lost round pin pj"],
    type: "shortboard",
    finSetup: "thruster",
    defaultLengthFt: 6.2,
    volumeBase: 28,
    volumePerFt: 0.85,
    waveRange: WAVE.stepUp,
    traits: T.stepUp,
    shaperNotes:
      "A round-pin step-up version of the PJ for bigger, more powerful surf. Extra length and refined tail hold for confident surfing in overhead conditions.",
    feelSummary:
      "Step-up round pin — hold and drive in bigger, more powerful surf.",
  }),
];
