import type { BoardModel } from "../types";
import { defineModel, T, WAVE } from "../helpers";

export const PYZEL_MODELS: BoardModel[] = [
  defineModel({
    id: "pyzel-ghost",
    brand: "Pyzel Surfboards",
    shaper: "Jon Pyzel / Pyzel",
    model: "Ghost",
    aliases: ["ghost", "pyzel ghost"],
    type: "shortboard",
    finSetup: "thruster",
    defaultLengthFt: 6.0,
    volumeBase: 26,
    volumePerFt: 0.95,
    waveRange: WAVE.performance,
    traits: T.driveShort,
    shaperNotes:
      "John John Florence's signature step-up shortboard — refined rails and rocker for powerful, good-quality surf. Built for hold and drive in overhead conditions.",
    feelSummary:
      "Power-surf step-up — hold and drive in overhead, quality waves.",
  }),
  defineModel({
    id: "pyzel-padillac",
    brand: "Pyzel Surfboards",
    shaper: "Jon Pyzel / Pyzel",
    model: "Padillac",
    aliases: ["padillac", "pyzel padillac"],
    type: "hybrid",
    finSetup: "thruster",
    defaultLengthFt: 6.2,
    volumeBase: 30,
    volumePerFt: 0.8,
    waveRange: WAVE.daily,
    traits: T.dailyHybrid,
    shaperNotes:
      "A high-volume hybrid with a wide outline for easy paddling in average surf. Pyzel designed it as a user-friendly step-down from a performance shortboard.",
    feelSummary:
      "Paddle-friendly hybrid — easy waves with Pyzel performance lines.",
  }),
  defineModel({
    id: "pyzel-phantom",
    brand: "Pyzel Surfboards",
    shaper: "Jon Pyzel / Pyzel",
    model: "Phantom",
    aliases: ["phantom", "pyzel phantom"],
    type: "shortboard",
    finSetup: "thruster",
    defaultLengthFt: 5.9,
    volumeBase: 25,
    volumePerFt: 1.0,
    waveRange: WAVE.performance,
    traits: T.hpShort,
    shaperNotes:
      "A high-performance shortboard with a refined outline for clean, punchy surf. Tight radius turns and strong rail engagement in good-quality waves.",
    feelSummary:
      "Clean-surf performer — snappy pocket turns and rail control.",
  }),
  defineModel({
    id: "pyzel-gremlin",
    brand: "Pyzel Surfboards",
    shaper: "Jon Pyzel / Pyzel",
    model: "Gremlin",
    aliases: ["gremlin", "pyzel gremlin"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 5.5,
    volumeBase: 24,
    volumePerFt: 1.1,
    waveRange: WAVE.grovel,
    traits: T.grovelHybrid,
    shaperNotes:
      "A wide, flat groveler with a quad setup for speed in small surf. Pyzel's small-wave weapon for generating planing speed in weak beach breaks.",
    feelSummary:
      "Small-wave quad groveler — wide, fast, and loose in mush.",
  }),
  defineModel({
    id: "pyzel-the-amp",
    brand: "Pyzel Surfboards",
    shaper: "Jon Pyzel / Pyzel",
    model: "The Amp",
    aliases: ["the amp", "amp", "pyzel amp"],
    type: "hybrid",
    finSetup: "thruster",
    defaultLengthFt: 5.67,
    volumeBase: 25,
    volumePerFt: 1.0,
    waveRange: WAVE.smallMed,
    traits: {
      speed: 8,
      pivot: 8,
      drive: 6,
      paddle: 7,
      hold: 5,
      grovel: 8,
      rail: 6,
    },
    shaperNotes:
      "An alternative small-wave design with a wide outline for speed and release. Built for progressive surfing in average beach-break conditions.",
    feelSummary:
      "Progressive small-wave hybrid — speed and skatey release.",
  }),
  defineModel({
    id: "pyzel-radius",
    brand: "Pyzel Surfboards",
    shaper: "Jon Pyzel / Pyzel",
    model: "Radius",
    aliases: ["radius", "pyzel radius"],
    type: "shortboard",
    finSetup: "thruster",
    defaultLengthFt: 6.0,
    volumeBase: 27,
    volumePerFt: 0.9,
    waveRange: WAVE.performance,
    traits: {
      speed: 7,
      pivot: 7,
      drive: 9,
      paddle: 6,
      hold: 9,
      grovel: 3,
      rail: 9,
    },
    shaperNotes:
      "A drive-focused performance shortboard with a fuller outline for powerful surf. Extra hold and projection through drawn-out turns in good waves.",
    feelSummary:
      "Drive-heavy performer — projects through turns in powerful surf.",
  }),
  defineModel({
    id: "pyzel-astro-pop",
    brand: "Pyzel Surfboards",
    shaper: "Jon Pyzel / Pyzel",
    model: "Astro Pop",
    aliases: ["astro pop", "astropop", "pyzel astro pop"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 5.67,
    volumeBase: 24,
    volumePerFt: 1.05,
    waveRange: WAVE.smallMed,
    traits: {
      speed: 8,
      pivot: 8,
      drive: 6,
      paddle: 7,
      hold: 5,
      grovel: 8,
      rail: 6,
    },
    shaperNotes:
      "A futuristic small-wave design with an alternative outline and quad fins. Generates speed through flat sections with a progressive, skatey feel.",
    feelSummary:
      "Futuristic quad hybrid — unconventional speed in average surf.",
  }),
  defineModel({
    id: "pyzel-shadow",
    brand: "Pyzel Surfboards",
    shaper: "Jon Pyzel / Pyzel",
    model: "Shadow",
    aliases: ["shadow", "pyzel shadow"],
    type: "shortboard",
    finSetup: "thruster",
    defaultLengthFt: 6.1,
    volumeBase: 28,
    volumePerFt: 0.85,
    waveRange: WAVE.stepUp,
    traits: T.stepUp,
    shaperNotes:
      "A step-up shortboard with extra length and refined rails for overhead surf. Built for hold and confidence when conditions push past everyday territory.",
    feelSummary:
      "Overhead step-up — hold and drive in bigger, more powerful surf.",
  }),
  defineModel({
    id: "pyzel-rounder",
    brand: "Pyzel Surfboards",
    shaper: "Jon Pyzel / Pyzel",
    model: "Rounder",
    aliases: ["rounder", "pyzel rounder"],
    type: "hybrid",
    finSetup: "thruster",
    defaultLengthFt: 6.0,
    volumeBase: 28,
    volumePerFt: 0.85,
    waveRange: WAVE.daily,
    traits: T.fun,
    shaperNotes:
      "A mellow, easy-riding hybrid with a rounder outline for casual sessions. Extra volume makes it approachable for intermediate surfers in average conditions.",
    feelSummary:
      "Easy-going daily hybrid — mellow turns and high wave count.",
  }),
];
