import type { BoardModel } from "../types";
import { defineModel, T, WAVE } from "../helpers";

export const RUSTY_MODELS: BoardModel[] = [
  defineModel({
    id: "rusty-miso",
    brand: "Rusty Surfboards",
    shaper: "Rusty Preisendorfer",
    model: "Miso",
    aliases: ["rusty miso", "rusty preisendorfer miso"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 5.8,
    volumeBase: 25,
    volumePerFt: 1.1,
    waveRange: WAVE.smallMed,
    traits: {
      speed: 9,
      pivot: 8,
      drive: 6,
      paddle: 8,
      hold: 4,
      grovel: 9,
      rail: 5,
    },
    shaperNotes:
      "Flat rocker and a wide, fishy tail built to generate speed in weak, gutless surf. Rusty designed it to stay loose and skatey in 2–4 ft — more glide than a shortboard, more snap than a traditional fish.",
    feelSummary:
      "Fast and loose in mush — generates speed where slower boards bog down.",
  }),
  defineModel({
    id: "rusty-dwart",
    brand: "Rusty Surfboards",
    shaper: "Rusty Preisendorfer",
    model: "Dwart",
    aliases: ["dwart", "rusty dwart"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 5.67,
    volumeBase: 25,
    volumePerFt: 1.0,
    waveRange: WAVE.grovel,
    traits: T.grovelHybrid,
    shaperNotes:
      "A wide, flat groveler with a quad setup for maximum speed in small surf. Rusty's answer to the soft-day dilemma — planes early and stays loose through flat sections.",
    feelSummary:
      "Wide, fast groveler — quad-driven speed in weak surf.",
  }),
  defineModel({
    id: "rusty-doinker",
    brand: "Rusty Surfboards",
    shaper: "Rusty Preisendorfer",
    model: "Doinker",
    aliases: ["doinker", "rusty doinker"],
    type: "hybrid",
    finSetup: "thruster",
    defaultLengthFt: 6.0,
    volumeBase: 28,
    volumePerFt: 0.85,
    waveRange: WAVE.daily,
    traits: T.dailyHybrid,
    shaperNotes:
      "A user-friendly hybrid with extra volume for easy paddling in average surf. Designed as a reliable daily driver for intermediate to advanced surfers.",
    feelSummary:
      "Forgiving daily hybrid — easy paddle with responsive turns.",
  }),
  defineModel({
    id: "rusty-hefeweizen",
    brand: "Rusty Surfboards",
    shaper: "Rusty Preisendorfer",
    model: "Hefeweizen",
    aliases: ["hefeweizen", "rusty hefeweizen"],
    type: "fish",
    finSetup: "twin",
    defaultLengthFt: 5.5,
    volumeBase: 23,
    volumePerFt: 1.1,
    waveRange: WAVE.grovel,
    traits: T.grovelFish,
    shaperNotes:
      "A wide, flat twin-keel fish for generating speed in tiny, weak surf. Light, lively, and built for the days when you just need to catch waves and have fun.",
    feelSummary:
      "Light, lively twin fish — glide and speed in the smallest surf.",
  }),
  defineModel({
    id: "rusty-panic-attack",
    brand: "Rusty Surfboards",
    shaper: "Rusty Preisendorfer",
    model: "Panic Attack",
    aliases: ["panic attack", "rusty panic attack"],
    type: "shortboard",
    finSetup: "thruster",
    defaultLengthFt: 5.9,
    volumeBase: 25,
    volumePerFt: 1.0,
    waveRange: WAVE.performance,
    traits: T.hpShort,
    shaperNotes:
      "A high-performance shortboard with a refined outline for clean, punchy surf. Built for tight pocket turns and confident rail work in good-quality waves.",
    feelSummary:
      "Snappy performance shortboard — rail-driven in clean surf.",
  }),
  defineModel({
    id: "rusty-pig-dog",
    brand: "Rusty Surfboards",
    shaper: "Rusty Preisendorfer",
    model: "Pig Dog",
    aliases: ["pig dog", "pigdog", "rusty pig dog"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 5.75,
    volumeBase: 26,
    volumePerFt: 0.95,
    waveRange: WAVE.smallMed,
    traits: {
      speed: 8,
      pivot: 7,
      drive: 7,
      paddle: 8,
      hold: 5,
      grovel: 7,
      rail: 6,
    },
    shaperNotes:
      "A wider, more voluminous hybrid for small-to-medium surf with extra paddle power. Rusty designed it for surfers who want performance without sacrificing wave count.",
    feelSummary:
      "Paddle-friendly hybrid — performance lines with extra volume.",
  }),
  defineModel({
    id: "rusty-fish-stix",
    brand: "Rusty Surfboards",
    shaper: "Rusty Preisendorfer",
    model: "Fish Stix",
    aliases: ["fish stix", "fishstix", "rusty fish stix"],
    type: "fish",
    finSetup: "twin",
    defaultLengthFt: 5.67,
    volumeBase: 24,
    volumePerFt: 1.05,
    waveRange: WAVE.smallMed,
    traits: T.perfFish,
    shaperNotes:
      "A modern performance fish with refined rails and a pulled-in tail. Faster and more maneuverable than a classic twin while keeping fish glide and release.",
    feelSummary:
      "Modern performance fish — speed and release with tighter turns.",
  }),
  defineModel({
    id: "rusty-d-honey",
    brand: "Rusty Surfboards",
    shaper: "Rusty Preisendorfer",
    model: "D Honey",
    aliases: ["d honey", "dhoney", "rusty d honey"],
    type: "hybrid",
    finSetup: "thruster",
    defaultLengthFt: 6.0,
    volumeBase: 27,
    volumePerFt: 0.9,
    waveRange: WAVE.daily,
    traits: {
      speed: 7,
      pivot: 7,
      drive: 8,
      paddle: 7,
      hold: 7,
      grovel: 5,
      rail: 7,
    },
    shaperNotes:
      "A smooth, flowing hybrid with a balanced outline for everyday surf. Enough performance for good waves with enough volume for average days.",
    feelSummary:
      "Smooth daily driver — balanced feel across a wide wave range.",
  }),
];
