import type { BoardModel } from "../types";
import { defineModel, T, WAVE } from "../helpers";

export const SLATER_DESIGNS_MODELS: BoardModel[] = [
  defineModel({
    id: "slater-s-boss",
    brand: "Slater Designs",
    shaper: "Kelly Slater / Slater Designs",
    model: "S Boss",
    aliases: ["s-boss", "sboss", "slater s boss"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 5.9,
    volumeBase: 24,
    volumePerFt: 1.0,
    waveRange: WAVE.smallMed,
    traits: T.grovelHybrid,
    shaperNotes:
      "Kelly Slater's small-wave groveler — wide, flat, and built to skate through soft sections. Quads keep it loose and quick off the tail in average California beach breaks.",
    feelSummary:
      "Skatey, pivoty small-wave performance — best when you need to manufacture speed.",
  }),
  defineModel({
    id: "slater-cymatic",
    brand: "Slater Designs",
    shaper: "Kelly Slater / Slater Designs",
    model: "Cymatic",
    aliases: ["slater cymatic"],
    type: "shortboard",
    finSetup: "thruster",
    defaultLengthFt: 5.83,
    volumeBase: 24,
    volumePerFt: 1.1,
    waveRange: WAVE.performance,
    traits: T.hpShort,
    shaperNotes:
      "High-performance shortboard geometry — tight radius turns, strong rail engagement, and confidence in punchy, good-quality surf. Not a groveler.",
    feelSummary:
      "Snappy, high-performance turns in clean, punchy surf.",
  }),
  defineModel({
    id: "slater-gamma",
    brand: "Slater Designs",
    shaper: "Kelly Slater / Slater Designs",
    model: "Gamma",
    aliases: ["slater gamma"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 6.0,
    volumeBase: 27,
    volumePerFt: 0.9,
    waveRange: WAVE.daily,
    traits: T.dailyHybrid,
    shaperNotes:
      "Daily-driver hybrid — blends paddle power with performance. Quads add drive without killing looseness in medium surf.",
    feelSummary:
      "Versatile hybrid — enough paddle for average days, enough performance when it cleans up.",
  }),
  defineModel({
    id: "slater-great-white",
    brand: "Slater Designs",
    shaper: "Kelly Slater / Slater Designs",
    model: "Great White",
    aliases: ["great white", "slater great white"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 6.2,
    volumeBase: 28,
    volumePerFt: 0.85,
    waveRange: WAVE.daily,
    traits: {
      speed: 8,
      pivot: 7,
      drive: 7,
      paddle: 8,
      hold: 6,
      grovel: 7,
      rail: 6,
    },
    shaperNotes:
      "A step-up hybrid with extra outline width and volume for bigger, more powerful surf. Designed to paddle early and hold through drawn-out turns when conditions push past everyday shortboard territory.",
    feelSummary:
      "Confident hybrid for medium-to-good surf with extra paddle and hold.",
  }),
  defineModel({
    id: "slater-banana",
    brand: "Slater Designs",
    shaper: "Kelly Slater / Slater Designs",
    model: "Banana",
    aliases: ["banana", "slater banana"],
    type: "fish",
    finSetup: "twin",
    defaultLengthFt: 5.5,
    volumeBase: 22,
    volumePerFt: 1.2,
    waveRange: WAVE.grovel,
    traits: T.grovelFish,
    shaperNotes:
      "A flat, wide twin-keel fish built for generating speed in weak, gutless surf. Kelly's take on a classic fish with modern rails for tighter turns than a retro twin.",
    feelSummary:
      "Fast, loose twin fish for soft, small surf — glide with skatey release.",
  }),
  defineModel({
    id: "slater-flat-earth",
    brand: "Slater Designs",
    shaper: "Kelly Slater / Slater Designs",
    model: "Flat Earth",
    aliases: ["flat earth", "slater flat earth"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 5.8,
    volumeBase: 25,
    volumePerFt: 1.0,
    waveRange: WAVE.grovel,
    traits: {
      speed: 9,
      pivot: 8,
      drive: 6,
      paddle: 8,
      hold: 4,
      grovel: 9,
      rail: 5,
    },
    shaperNotes:
      "Ultra-flat rocker and wide outline for maximum planing speed in marginal surf. Built as a grovel weapon when you need to stay on top of soft, flat sections.",
    feelSummary:
      "Flat, fast, and loose — a grovel specialist for the weakest days.",
  }),
  defineModel({
    id: "slater-pro-spitfire",
    brand: "Slater Designs",
    shaper: "Kelly Slater / Slater Designs",
    model: "Pro Spitfire",
    aliases: ["pro spitfire", "spitfire pro", "slater pro spitfire"],
    type: "shortboard",
    finSetup: "thruster",
    defaultLengthFt: 5.9,
    volumeBase: 25,
    volumePerFt: 1.0,
    waveRange: WAVE.performance,
    traits: {
      speed: 8,
      pivot: 8,
      drive: 8,
      paddle: 6,
      hold: 8,
      grovel: 4,
      rail: 8,
    },
    shaperNotes:
      "A refined performance shortboard with a slightly wider nose and tail for everyday good surf. Tighter than a groveler but more forgiving than a pure contest stick.",
    feelSummary:
      "Balanced performance shortboard for clean, everyday surf.",
  }),
  defineModel({
    id: "slater-seaside",
    brand: "Slater Designs",
    shaper: "Kelly Slater / Slater Designs",
    model: "Seaside",
    aliases: ["seaside", "slater seaside", "sd seaside"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 5.67,
    volumeBase: 24,
    volumePerFt: 1.05,
    waveRange: WAVE.smallMed,
    traits: {
      speed: 8,
      pivot: 8,
      drive: 6,
      paddle: 7,
      hold: 5,
      grovel: 8,
      rail: 6,
    },
    shaperNotes:
      "Slater Designs crossover of the Firewire Seaside — wide, flat, and quad-driven for small-to-medium surf. Blends fish speed with shortboard maneuverability.",
    feelSummary:
      "Quick, skatey hybrid for average beach breaks — fishy speed with quad looseness.",
  }),
  defineModel({
    id: "slater-seasick",
    brand: "Slater Designs",
    shaper: "Kelly Slater / Slater Designs",
    model: "Seasick",
    aliases: ["seasick", "slater seasick"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 5.75,
    volumeBase: 25,
    volumePerFt: 1.0,
    waveRange: WAVE.grovel,
    traits: {
      speed: 9,
      pivot: 9,
      drive: 5,
      paddle: 7,
      hold: 4,
      grovel: 9,
      rail: 5,
    },
    shaperNotes:
      "An experimental small-wave design with an asymmetric outline for generating speed and release in weak surf. Built for riders who want something different in gutless conditions.",
    feelSummary:
      "Asymmetric groveler — unconventional speed and release in mush.",
  }),
  defineModel({
    id: "slater-frk",
    brand: "Slater Designs",
    shaper: "Kelly Slater / Slater Designs",
    model: "FRK",
    aliases: ["frk", "slater frk", "firewire frk"],
    type: "shortboard",
    finSetup: "thruster",
    defaultLengthFt: 6.0,
    volumeBase: 26,
    volumePerFt: 0.95,
    waveRange: WAVE.performance,
    traits: T.driveShort,
    shaperNotes:
      "A performance shortboard with a fuller outline and forgiving rails for good-quality surf. Designed as a reliable daily driver when waves have push and shape.",
    feelSummary:
      "Drivey, forgiving performance shortboard for solid everyday surf.",
  }),
];
