import type { BoardModel } from "../types";
import { defineModel, T, WAVE } from "../helpers";

export const TIMMY_PATTERSON_MODELS: BoardModel[] = [
  defineModel({
    id: "timmy-patterson-provado",
    brand: "Timmy Patterson Surfboards",
    shaper: "Timmy Patterson",
    model: "Provado",
    aliases: ["provado", "timmy patterson provado"],
    type: "shortboard",
    finSetup: "thruster",
    defaultLengthFt: 5.9,
    volumeBase: 25,
    volumePerFt: 1.0,
    waveRange: WAVE.performance,
    traits: T.hpShort,
    shaperNotes:
      "Timmy Patterson's high-performance shortboard with a refined outline for clean, punchy surf. Built for tight pocket turns and confident rail work.",
    feelSummary:
      "Snappy performance shortboard — rail-driven in clean surf.",
  }),
  defineModel({
    id: "timmy-patterson-dm3",
    brand: "Timmy Patterson Surfboards",
    shaper: "Timmy Patterson",
    model: "DM3",
    aliases: ["dm3", "timmy patterson dm3"],
    type: "shortboard",
    finSetup: "thruster",
    defaultLengthFt: 6.0,
    volumeBase: 26,
    volumePerFt: 0.95,
    waveRange: WAVE.performance,
    traits: T.driveShort,
    shaperNotes:
      "A drive-focused performance shortboard with a slightly fuller outline for powerful surf. Extra hold and projection through drawn-out turns in good waves.",
    feelSummary:
      "Drivey performer — projects through turns in powerful surf.",
  }),
  defineModel({
    id: "timmy-patterson-new-flyer",
    brand: "Timmy Patterson Surfboards",
    shaper: "Timmy Patterson",
    model: "New Flyer",
    aliases: ["new flyer", "newflyer", "timmy patterson new flyer"],
    type: "hybrid",
    finSetup: "thruster",
    defaultLengthFt: 6.0,
    volumeBase: 28,
    volumePerFt: 0.85,
    waveRange: WAVE.daily,
    traits: T.dailyHybrid,
    shaperNotes:
      "An updated flyer-style hybrid with extra volume for easy paddling in average surf. Designed as a user-friendly daily driver with performance heritage.",
    feelSummary:
      "Easy-paddling hybrid — flyer speed with everyday forgiveness.",
  }),
  defineModel({
    id: "timmy-patterson-m3",
    brand: "Timmy Patterson Surfboards",
    shaper: "Timmy Patterson",
    model: "M3",
    aliases: ["m3", "timmy patterson m3"],
    type: "shortboard",
    finSetup: "thruster",
    defaultLengthFt: 6.0,
    volumeBase: 27,
    volumePerFt: 0.9,
    waveRange: WAVE.stepUp,
    traits: T.stepUp,
    shaperNotes:
      "A step-up shortboard with extra length and refined rails for overhead surf. Built for hold and drive when conditions push past everyday territory.",
    feelSummary:
      "Confident step-up — hold and drive in overhead surf.",
  }),
  defineModel({
    id: "timmy-patterson-smooth-operator",
    brand: "Timmy Patterson Surfboards",
    shaper: "Timmy Patterson",
    model: "Smooth Operator",
    aliases: ["smooth operator", "smoothoperator", "timmy patterson smooth operator"],
    type: "hybrid",
    finSetup: "thruster",
    defaultLengthFt: 6.2,
    volumeBase: 30,
    volumePerFt: 0.8,
    waveRange: WAVE.daily,
    traits: T.fun,
    shaperNotes:
      "A mellow, easy-riding hybrid for casual sessions and softer waves. Extra volume and a relaxed rocker make it approachable for intermediate surfers.",
    feelSummary:
      "Smooth daily cruiser — easy waves and flowing turns.",
  }),
  defineModel({
    id: "timmy-patterson-flyer",
    brand: "Timmy Patterson Surfboards",
    shaper: "Timmy Patterson",
    model: "Flyer",
    aliases: ["flyer", "timmy patterson flyer"],
    type: "hybrid",
    finSetup: "thruster",
    defaultLengthFt: 5.9,
    volumeBase: 27,
    volumePerFt: 0.9,
    waveRange: WAVE.daily,
    traits: {
      speed: 8,
      pivot: 7,
      drive: 7,
      paddle: 8,
      hold: 6,
      grovel: 6,
      rail: 7,
    },
    shaperNotes:
      "Patterson's classic flyer hybrid — a balanced outline for everyday surf with enough performance for good waves. A longtime San Diego favorite.",
    feelSummary:
      "Classic SD flyer — balanced feel for everyday conditions.",
  }),
  defineModel({
    id: "timmy-patterson-sub-flyer",
    brand: "Timmy Patterson Surfboards",
    shaper: "Timmy Patterson",
    model: "Sub Flyer",
    aliases: ["sub flyer", "subflyer", "timmy patterson sub flyer"],
    type: "hybrid",
    finSetup: "thruster",
    defaultLengthFt: 5.67,
    volumeBase: 26,
    volumePerFt: 0.95,
    waveRange: WAVE.smallMed,
    traits: {
      speed: 8,
      pivot: 7,
      drive: 7,
      paddle: 8,
      hold: 5,
      grovel: 7,
      rail: 6,
    },
    shaperNotes:
      "A step-down flyer with extra width and volume for small-to-medium surf. Easier paddling with the same responsive feel as the original Flyer.",
    feelSummary:
      "Step-down flyer — easier paddle for small-to-medium surf.",
  }),
  defineModel({
    id: "timmy-patterson-groveler",
    brand: "Timmy Patterson Surfboards",
    shaper: "Timmy Patterson",
    model: "Groveler",
    aliases: ["groveler", "timmy patterson groveler"],
    type: "hybrid",
    finSetup: "quad",
    defaultLengthFt: 5.5,
    volumeBase: 24,
    volumePerFt: 1.1,
    waveRange: WAVE.grovel,
    traits: T.grovelHybrid,
    shaperNotes:
      "A wide, flat grovel board with a quad setup for speed in weak surf. Patterson's small-wave weapon for San Diego's mushiest days.",
    feelSummary:
      "SD grovel quad — wide and fast in weak beach breaks.",
  }),
  defineModel({
    id: "timmy-patterson-round-pin",
    brand: "Timmy Patterson Surfboards",
    shaper: "Timmy Patterson",
    model: "Round Pin",
    aliases: ["round pin", "roundpin", "timmy patterson round pin"],
    type: "shortboard",
    finSetup: "thruster",
    defaultLengthFt: 6.4,
    volumeBase: 30,
    volumePerFt: 0.75,
    waveRange: WAVE.stepUp,
    traits: {
      speed: 6,
      pivot: 6,
      drive: 9,
      paddle: 6,
      hold: 10,
      grovel: 2,
      rail: 8,
    },
    shaperNotes:
      "A round-pin step-up for bigger, more powerful surf with drawn-out turns. Extra length and refined tail hold for confident surfing in overhead conditions.",
    feelSummary:
      "Round-pin step-up — hold and drive in bigger, powerful surf.",
  }),
];
