import type { BreakType, TidePreference } from "@/lib/spot-profiles/types";

/** Structured spot specs for swell/tide matching and Sage comparisons. */
export interface SpotSpec {
  catalogId: string;
  name: string;
  aliases: string[];
  region: string;
  breakType: BreakType;
  swellDegMin: number;
  swellDegMax: number;
  tidePreference: TidePreference;
  tideNotes: string;
  howItBreaks: string;
  minPeriodSec: number;
  amplificationFactor: number;
  shadowSensitivity: number;
}

/**
 * SoCal catalog spot specs (San Diego + Orange County + select LA).
 * Swell bearings are meteorological degrees. ±10–15° tolerance in scoring.
 */
export const SPOT_SPECS: SpotSpec[] = [
  // —— San Diego North County ——
  {
    catalogId: "tamarack",
    name: "Tamarack",
    aliases: ["tamarack beach", "carlsbad village tamarack", "carlsbad tamarack"],
    region: "San Diego",
    breakType: "beach",
    // Open west-facing beach — summer S–SSW and winter W–NW both work.
    swellDegMin: 180,
    swellDegMax: 310,
    tidePreference: "mid",
    tideNotes: "Mid tide when sandbars line up for long rights/lefts.",
    howItBreaks:
      "Sandbar beach break in Carlsbad; long rights/lefts when sand lines up. Fun on summer SSW and winter W–NW.",
    minPeriodSec: 8,
    amplificationFactor: 1.05,
    shadowSensitivity: 0.65,
  },
  {
    catalogId: "grandview",
    name: "Grandview",
    aliases: ["grand view", "pipes", "pipe", "san elijo", "grandview encinitas"],
    region: "San Diego",
    breakType: "reef",
    swellDegMin: 200,
    swellDegMax: 310,
    tidePreference: "mid",
    tideNotes: "Mid to high tide over reef; low exposes rock.",
    howItBreaks:
      "Mixed reef/rock and beach peaks (San Elijo / Pipes area); punchy on SSW–W through NW when clean.",
    minPeriodSec: 9,
    amplificationFactor: 1.08,
    shadowSensitivity: 0.75,
  },
  {
    catalogId: "swamis",
    name: "Swami's",
    aliases: ["swamis", "swami's", "encinitas swamis"],
    region: "San Diego",
    breakType: "point",
    swellDegMin: 200,
    swellDegMax: 315,
    tidePreference: "mid",
    tideNotes: "Mid to high tide for best point lines.",
    howItBreaks:
      "Long right-hand point; classic on WNW–NW, also links on solid SSW–SW wrap.",
    minPeriodSec: 10,
    amplificationFactor: 1.14,
    shadowSensitivity: 0.8,
  },
  {
    catalogId: "beacons",
    name: "Beacons",
    aliases: ["beacons beach", "beacon's", "leucadia beacons"],
    region: "San Diego",
    breakType: "reef",
    swellDegMin: 200,
    swellDegMax: 310,
    tidePreference: "mid",
    tideNotes: "Mid tide; sensitive to swell size and sand.",
    howItBreaks: "Small reef peaks north of Swami's; works on SSW–W through NW.",
    minPeriodSec: 9,
    amplificationFactor: 1.06,
    shadowSensitivity: 0.75,
  },
  {
    catalogId: "d-street",
    name: "D Street",
    aliases: ["d street", "d-street", "d st", "seaside encinitas", "main seaside"],
    region: "San Diego",
    breakType: "beach",
    swellDegMin: 180,
    swellDegMax: 310,
    tidePreference: "mid",
    tideNotes: "Mid tide; cobble and beach peaks vary with sand.",
    howItBreaks:
      "Encinitas cobble reef and beach peaks; variable rides depending on sand and swell period.",
    minPeriodSec: 8,
    amplificationFactor: 1.0,
    shadowSensitivity: 0.65,
  },
  {
    catalogId: "cardiff",
    name: "Cardiff Reef",
    aliases: ["cardiff", "cardiff reef", "cardiff state beach"],
    region: "San Diego",
    breakType: "reef",
    swellDegMin: 200,
    swellDegMax: 310,
    tidePreference: "mid",
    tideNotes: "Mid to high tide over cobble; low gets fast and shallow.",
    howItBreaks:
      "Right-hand reef/cobble peak; rippable on SSW–W through WNW when clean.",
    minPeriodSec: 9,
    amplificationFactor: 1.12,
    shadowSensitivity: 0.75,
  },
  {
    catalogId: "seaside-reef",
    name: "Seaside Reef",
    aliases: ["seaside", "seaside reef", "stone steps", "seaside stone steps"],
    region: "San Diego",
    breakType: "reef",
    swellDegMin: 200,
    swellDegMax: 310,
    tidePreference: "mid",
    tideNotes: "Mid tide; short punchy peaks over cobble.",
    howItBreaks:
      "Short, punchy cobble peaks; works on SSW–W through NW on cleaner days.",
    minPeriodSec: 9,
    amplificationFactor: 1.08,
    shadowSensitivity: 0.75,
  },
  {
    catalogId: "ponto-jetty",
    name: "Ponto Jetty",
    aliases: ["ponto", "ponto jetty", "south ponto", "carlsbad ponto"],
    region: "San Diego",
    breakType: "jetty",
    swellDegMin: 200,
    swellDegMax: 315,
    tidePreference: "mid",
    tideNotes: "Mid tide; low exposes jetty rocks.",
    howItBreaks:
      "Jetty-influenced rights/lefts; summer SSW and winter W–NW both light peaks when sand aligns.",
    minPeriodSec: 8,
    amplificationFactor: 1.12,
    shadowSensitivity: 0.7,
  },
  {
    catalogId: "oceanside",
    name: "Oceanside Pier",
    aliases: ["oceanside", "oceanside pier", "oside pier"],
    region: "San Diego",
    breakType: "beach",
    swellDegMin: 180,
    swellDegMax: 310,
    tidePreference: "mid",
    tideNotes: "Mid to low tide for peaky northside sandbars.",
    howItBreaks:
      "Beach-break peaks on both sides of the pier; fun on summer SSW and winter W–NW.",
    minPeriodSec: 8,
    amplificationFactor: 1.05,
    shadowSensitivity: 0.65,
  },
  {
    catalogId: "oceanside-harbor",
    name: "Oceanside Harbor",
    aliases: ["oceanside harbor", "oside harbor", "breakwater oceanside"],
    region: "San Diego",
    breakType: "jetty",
    swellDegMin: 250,
    swellDegMax: 320,
    tidePreference: "mid",
    tideNotes: "Mid to low for sandbar shaping; watch harbor currents.",
    howItBreaks:
      "Point/jetty-enhanced peaks near harbor mouth; prefers W–NW but takes SW wrap on bigger days.",
    minPeriodSec: 8,
    amplificationFactor: 1.1,
    shadowSensitivity: 0.75,
  },
  {
    catalogId: "the-rock",
    name: "The Rock",
    aliases: ["the rock", "rock oceanside"],
    region: "San Diego",
    breakType: "beach",
    swellDegMin: 200,
    swellDegMax: 315,
    tidePreference: "mid",
    tideNotes:
      "Mid to low tide — the exposed rock helps shape peaks; high tide softens and buries the structure.",
    howItBreaks:
      "Exposed Oceanside beach break. An exposed rock helps shape and wedge peaks on mid to low tide when sand and swell align — not a reef break.",
    minPeriodSec: 8,
    amplificationFactor: 1.05,
    shadowSensitivity: 0.7,
  },
  {
    catalogId: "terramar",
    name: "Terramar",
    aliases: ["terramar point", "terramar carlsbad"],
    region: "San Diego",
    breakType: "reef",
    swellDegMin: 200,
    swellDegMax: 310,
    tidePreference: "mid",
    tideNotes: "Mid tide typical for reef peaks.",
    howItBreaks: "Carlsbad reef with lined-up rights/lefts on SSW–W through WNW.",
    minPeriodSec: 9,
    amplificationFactor: 1.1,
    shadowSensitivity: 0.75,
  },
  {
    catalogId: "del-mar",
    name: "Del Mar",
    aliases: ["del mar", "del mar beach"],
    region: "San Diego",
    breakType: "beach",
    swellDegMin: 180,
    swellDegMax: 310,
    tidePreference: "mid",
    tideNotes: "Mid tide; sandbars shift seasonally.",
    howItBreaks: "Mixed reef and beach peaks along the Del Mar strip; open to summer SSW.",
    minPeriodSec: 8,
    amplificationFactor: 1.0,
    shadowSensitivity: 0.65,
  },
  {
    catalogId: "del-mar-jetty",
    name: "Del Mar Jetty",
    aliases: ["del mar jetty", "dm jetty"],
    region: "San Diego",
    breakType: "jetty",
    swellDegMin: 200,
    swellDegMax: 310,
    tidePreference: "mid",
    tideNotes: "Mid tide; jetty sand shifts.",
    howItBreaks: "Jetty wedges when sand is stacked and swell has NW angle.",
    minPeriodSec: 8,
    amplificationFactor: 1.12,
    shadowSensitivity: 0.8,
  },
  // —— San Diego Central ——
  {
    catalogId: "blacks-beach",
    name: "Black's Beach",
    aliases: [
      "blacks",
      "black's",
      "blacks beach",
      "black's beach",
      "torrey pines",
    ],
    region: "San Diego",
    breakType: "beach",
    // Canyon-focused: summer S–SSW and winter W–NW both light it up.
    swellDegMin: 180,
    swellDegMax: 320,
    tidePreference: "mid",
    tideNotes: "Mid to high for safer takeoffs; low is very shallow.",
    howItBreaks:
      "Powerful, steep sandbar beach break under the cliffs; Torrey Pines canyon focuses S–SSW through W–NW energy.",
    minPeriodSec: 10,
    amplificationFactor: 1.2,
    shadowSensitivity: 0.75,
  },
  {
    catalogId: "windansea",
    name: "Windansea",
    aliases: ["windansea", "windan sea", "wind and sea"],
    region: "San Diego",
    breakType: "reef",
    swellDegMin: 200,
    swellDegMax: 315,
    tidePreference: "mid",
    tideNotes: "Mid to high safer over rocks; low exposes reef.",
    howItBreaks:
      "Rocky reef / shallow cobble peak; works on SSW–SW wrap and classic WNW–NW days.",
    minPeriodSec: 10,
    amplificationFactor: 1.12,
    shadowSensitivity: 0.85,
  },
  {
    catalogId: "scripps-pier",
    name: "Scripps Pier",
    aliases: ["scripps", "scripps pier", "la jolla scripps"],
    region: "San Diego",
    breakType: "beach",
    swellDegMin: 200,
    swellDegMax: 310,
    tidePreference: "mid",
    tideNotes: "Mid tide for reef-influenced peaks.",
    howItBreaks:
      "Point/reef-influenced rights and lefts near the pier; rippable on SSW–W through NW when wind is friendly.",
    minPeriodSec: 8,
    amplificationFactor: 1.02,
    shadowSensitivity: 0.72,
  },
  {
    catalogId: "pacific-beach",
    name: "Pacific Beach",
    aliases: ["pacific beach", "pb", "pb pier", "crystal pier", "tourmaline"],
    region: "San Diego",
    breakType: "beach",
    swellDegMin: 270,
    swellDegMax: 300,
    tidePreference: "mid",
    tideNotes: "Mid to low for cleaner sandbar peaks.",
    howItBreaks:
      "Open beach peaks; Tourmaline north end mellower, pier area more punchy.",
    minPeriodSec: 8,
    amplificationFactor: 1.0,
    shadowSensitivity: 0.7,
  },
  {
    catalogId: "mission-jetty",
    name: "Mission Jetty",
    aliases: ["mission jetty", "mission beach", "south mission", "belmont park"],
    region: "San Diego",
    breakType: "jetty",
    swellDegMin: 270,
    swellDegMax: 300,
    tidePreference: "mid",
    tideNotes: "Mid to low for jetty sandbar wedges.",
    howItBreaks: "Jetty sandbars with fun short rights/lefts when sand is stacked.",
    minPeriodSec: 8,
    amplificationFactor: 1.1,
    shadowSensitivity: 0.78,
  },
  {
    catalogId: "ocean-beach",
    name: "Ocean Beach",
    aliases: ["ocean beach", "ob", "ob pier", "ocean beach pier", "sunset cliffs"],
    region: "San Diego",
    breakType: "beach",
    swellDegMin: 285,
    swellDegMax: 305,
    tidePreference: "mid",
    tideNotes: "Mid to low for peaky sandbar rides; high pushes inside.",
    howItBreaks:
      "Long beach-break peaks; can hold bigger NW swell when sandbars align.",
    minPeriodSec: 8,
    amplificationFactor: 1.02,
    shadowSensitivity: 0.72,
  },
  // —— Orange County ——
  {
    catalogId: "trestles",
    name: "Lower Trestles",
    aliases: ["lowers", "lower trestles", "trestles", "cottons"],
    region: "Orange County",
    breakType: "point",
    swellDegMin: 170,
    swellDegMax: 315,
    tidePreference: "mid",
    tideNotes: "Mid to high tide for optimal cobble faces.",
    howItBreaks:
      "High-performance cobble point; long hollow rights and lefts. Classic on S–SW summer groundswell; also fires on WNW–NW winter swell.",
    minPeriodSec: 10,
    amplificationFactor: 1.15,
    shadowSensitivity: 0.85,
  },
  {
    catalogId: "trestles-uppers",
    name: "Uppers",
    aliases: ["uppers", "upper trestles", "church trestles"],
    region: "Orange County",
    breakType: "point",
    swellDegMin: 170,
    swellDegMax: 315,
    tidePreference: "mid",
    tideNotes: "Mid tide; cleaner on incoming.",
    howItBreaks: "Faster reef/cobble point peaks; more critical than Lowers.",
    minPeriodSec: 10,
    amplificationFactor: 1.12,
    shadowSensitivity: 0.85,
  },
  {
    catalogId: "trestles-middles",
    name: "Middles",
    aliases: ["middles", "middle trestles"],
    region: "Orange County",
    breakType: "point",
    swellDegMin: 170,
    swellDegMax: 315,
    tidePreference: "mid",
    tideNotes: "Mid to low depending on sand influence.",
    howItBreaks: "Mellower Trestles section; forgiving walls when other peaks are maxed.",
    minPeriodSec: 10,
    amplificationFactor: 1.08,
    shadowSensitivity: 0.88,
  },
  {
    catalogId: "salt-creek",
    name: "Salt Creek",
    aliases: ["salt creek", "dana point salt creek"],
    region: "Orange County",
    breakType: "reef",
    swellDegMin: 285,
    swellDegMax: 315,
    tidePreference: "mid",
    tideNotes: "Mid to high tide over reef.",
    howItBreaks: "Powerful Dana Point rights with hollow sections on NW groundswell.",
    minPeriodSec: 10,
    amplificationFactor: 1.12,
    shadowSensitivity: 0.88,
  },
  {
    catalogId: "huntington",
    name: "Huntington Beach",
    aliases: ["huntington", "hb", "huntington pier", "bolsa chica"],
    region: "Orange County",
    breakType: "beach",
    swellDegMin: 270,
    swellDegMax: 305,
    tidePreference: "mid",
    tideNotes: "Mid to low for peaky pier sandbars.",
    howItBreaks:
      "Classic beach break; long rippable peaks on W–WNW groundswell.",
    minPeriodSec: 8,
    amplificationFactor: 1.05,
    shadowSensitivity: 0.72,
  },
  {
    catalogId: "newport",
    name: "Newport Beach",
    aliases: ["newport", "newport pier", "54th street newport"],
    region: "Orange County",
    breakType: "beach",
    swellDegMin: 270,
    swellDegMax: 300,
    tidePreference: "mid",
    tideNotes: "Mid to low for sandbar peaks (not The Wedge).",
    howItBreaks:
      "Sandbar beach peaks; longboard-friendly on smaller W–WNW swell.",
    minPeriodSec: 8,
    amplificationFactor: 1.0,
    shadowSensitivity: 0.72,
  },
  // —— LA / South Bay (defaults from regional knowledge) ——
  {
    catalogId: "malibu",
    name: "Malibu",
    aliases: ["malibu", "first point"],
    region: "LA / Ventura",
    breakType: "point",
    swellDegMin: 250,
    swellDegMax: 310,
    tidePreference: "mid",
    tideNotes: "Mid tide for point peel.",
    howItBreaks: "Classic right point; long walls on SW–W swells.",
    minPeriodSec: 9,
    amplificationFactor: 1.12,
    shadowSensitivity: 0.85,
  },
  {
    catalogId: "venice",
    name: "Venice Beach",
    aliases: ["venice"],
    region: "South Bay",
    breakType: "beach",
    swellDegMin: 270,
    swellDegMax: 300,
    tidePreference: "mid",
    tideNotes: "Mid tide sandbar peaks.",
    howItBreaks: "Open beach break peaks.",
    minPeriodSec: 8,
    amplificationFactor: 1.0,
    shadowSensitivity: 0.7,
  },
  {
    catalogId: "manhattan",
    name: "Manhattan Beach",
    aliases: ["manhattan"],
    region: "South Bay",
    breakType: "beach",
    swellDegMin: 270,
    swellDegMax: 300,
    tidePreference: "mid",
    tideNotes: "Mid tide.",
    howItBreaks: "South Bay sandbar beach break.",
    minPeriodSec: 8,
    amplificationFactor: 1.0,
    shadowSensitivity: 0.7,
  },
  {
    catalogId: "hermosa",
    name: "Hermosa Beach",
    aliases: ["hermosa"],
    region: "South Bay",
    breakType: "beach",
    swellDegMin: 270,
    swellDegMax: 300,
    tidePreference: "mid",
    tideNotes: "Mid tide.",
    howItBreaks: "Beach break peaks; pier influence nearby.",
    minPeriodSec: 8,
    amplificationFactor: 1.0,
    shadowSensitivity: 0.7,
  },
  {
    catalogId: "redondo",
    name: "Redondo Beach",
    aliases: ["redondo"],
    region: "South Bay",
    breakType: "beach",
    swellDegMin: 270,
    swellDegMax: 300,
    tidePreference: "mid",
    tideNotes: "Mid tide.",
    howItBreaks: "South Bay beach break.",
    minPeriodSec: 8,
    amplificationFactor: 1.0,
    shadowSensitivity: 0.7,
  },
  {
    catalogId: "palos-verdes",
    name: "Palos Verdes",
    aliases: ["pv", "palos verdes", "lunada bay"],
    region: "South Bay",
    breakType: "point",
    swellDegMin: 240,
    swellDegMax: 300,
    tidePreference: "mid",
    tideNotes: "Mid tide on reef/point setups.",
    howItBreaks: "Reef and point breaks along the PV peninsula.",
    minPeriodSec: 10,
    amplificationFactor: 1.08,
    shadowSensitivity: 0.85,
  },
  {
    catalogId: "ventura",
    name: "Ventura Point",
    aliases: ["ventura", "c-street"],
    region: "LA / Ventura",
    breakType: "point",
    swellDegMin: 240,
    swellDegMax: 300,
    tidePreference: "mid",
    tideNotes: "Mid tide.",
    howItBreaks: "Point break with long walls on W–NW swell.",
    minPeriodSec: 9,
    amplificationFactor: 1.1,
    shadowSensitivity: 0.8,
  },
];

const BY_CATALOG_ID = new Map(SPOT_SPECS.map((s) => [s.catalogId, s]));

export function getSpotSpec(catalogId: string): SpotSpec | undefined {
  return BY_CATALOG_ID.get(catalogId);
}

export function findSpotSpecInText(text: string): SpotSpec | undefined {
  const lower = text.toLowerCase();
  const ranked = [...SPOT_SPECS].sort((a, b) => b.name.length - a.name.length);
  for (const spec of ranked) {
    if (lower.includes(spec.name.toLowerCase())) return spec;
    if (spec.aliases.some((a) => lower.includes(a))) return spec;
  }
  return undefined;
}
